objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Brand</fullName>
        <active>true</active>
        <description>Accounts for Brands</description>
        <label>Brand</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Brand_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Brand_Id__c</fullName>
        <label>Brand Id</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Privacy_Auto_Response_Email_Template__c</fullName>
        <label>Privacy Auto Response Email Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Brand Setting</label>
    <pluralLabel>Brand Settings</pluralLabel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <description>This field is used to show Country in Personal Data Request Form</description>
        <inlineHelpText>Need to Select the Country of Residence</inlineHelpText>
        <label>Country of Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>United States of America (USA)</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia &amp; Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Data Owner's Contact Record</description>
        <label>Data Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Privacy Requests</relationshipLabel>
        <relationshipName>PrivacyRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Perfect_Match_Found__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether a Perfect Match was found for the privacy request</description>
        <label>Perfect Match Found</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Rejected Request</fullName>
                </value>
                <value>
                    <fullName>No Response to follow-up</fullName>
                </value>
                <value>
                    <fullName>Data Not Found</fullName>
                </value>
                <value>
                    <fullName>User Data Provided</fullName>
                </value>
                <value>
                    <fullName>User Data Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Availability Questions</fullName>
                </value>
                <value>
                    <fullName>Quality Concerns</fullName>
                </value>
                <value>
                    <fullName>Sizing Questions</fullName>
                </value>
                <value>
                    <fullName>Care Instructions</fullName>
                </value>
                <value>
                    <fullName>Product Feedback</fullName>
                </value>
                <value>
                    <fullName>Problem Placing Order</fullName>
                </value>
                <value>
                    <fullName>Tracking Order Shipment</fullName>
                </value>
                <value>
                    <fullName>Edit Existing Order</fullName>
                </value>
                <value>
                    <fullName>Cancel Order</fullName>
                </value>
                <value>
                    <fullName>Missing/Damaged Product</fullName>
                </value>
                <value>
                    <fullName>Return Policy</fullName>
                </value>
                <value>
                    <fullName>Returning Order</fullName>
                </value>
                <value>
                    <fullName>Creating Return Label</fullName>
                </value>
                <value>
                    <fullName>Tracking Return</fullName>
                </value>
                <value>
                    <fullName>Return Status</fullName>
                </value>
                <value>
                    <fullName>Signing Up</fullName>
                </value>
                <value>
                    <fullName>Program Questions</fullName>
                </value>
                <value>
                    <fullName>Adding Points</fullName>
                </value>
                <value>
                    <fullName>Redeeming Rewards</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Update Information</fullName>
                </value>
                <value>
                    <fullName>Problem Receiving</fullName>
                </value>
                <value>
                    <fullName>Unsubscribe</fullName>
                </value>
                <value>
                    <fullName>Access My Data</fullName>
                </value>
                <value>
                    <fullName>Delete My Data</fullName>
                </value>
                <value>
                    <fullName>Data Owner Request</fullName>
                </value>
                <value>
                    <fullName>Privacy Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>emailToAddress__c</fullName>
        <label>emailToAddress</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Additional_Email_1__c</fullName>
        <description>The first additional email to send data owner requests to</description>
        <label>Additional Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Additional_Email_2__c</fullName>
        <description>The second additional email to send data owner requests to</description>
        <label>Additional Email 2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Additional_Email_3__c</fullName>
        <description>The third additional email to send data owner requests to</description>
        <label>Additional Email 3</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Additional_Email_4__c</fullName>
        <description>The fourth additional email to send data owner requests to</description>
        <label>Additional Email 4</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Brand_Id__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bass</fullName>
                </value>
                <value>
                    <fullName>Calvin Klein</fullName>
                    <label>Calvin Klein</label>
                </value>
                <value>
                    <fullName>Heritage Ecom</fullName>
                </value>
                <value>
                    <fullName>Izod</fullName>
                </value>
                <value>
                    <fullName>IZOD.com</fullName>
                </value>
                <value>
                    <fullName>Partner Brands</fullName>
                    <label>Partner Brands</label>
                </value>
                <value>
                    <fullName>Speedo</fullName>
                </value>
                <value>
                    <fullName>Style Bureau</fullName>
                    <label>Style Bureau</label>
                </value>
                <value>
                    <fullName>Tommy Hilfiger</fullName>
                </value>
                <value>
                    <fullName>Van Heusen</fullName>
                </value>
                <value>
                    <fullName>Van Heusen.com</fullName>
                    <label>Van Heusen.com</label>
                </value>
                <value>
                    <fullName>Warners.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <fields>
        <fullName>System_Type__c</fullName>
        <description>The type of system for which the Data Owner is Responsible</description>
        <label>System Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
                <value>
                    <fullName>External - Managed By PVH</fullName>
                </value>
                <value>
                    <fullName>Supplemental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Brand_Id.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

classes/PrivacyCaseTriggerHandler.cls
/**
* @author Magnet360
* @date 2019
*
* @group Case
* @group-content ../../ApexDocContent/Case.htm
*
* @description Privacy-specific case trigger handler. This class only runs once per
* Case DML where the CaseTriggerHandler may run multiple times. The primary reason for this
* class being separate is to ensure we do not send multiple automated emails.
*/
public class PrivacyCaseTriggerHandler {

    public static Boolean isFirstRun = True;
    /***********************************************************************************************
    * @description Primary method, called by CaseTrigger in
    * the AfterUpdate cycle of Insert and Update on case.
    * Determines if work is needed and calls the appropriate methods.
    */
    public static void sendEmailsIfNecessary() {
        List<Case> privacyCases = new List<Case>();
        List<Id> newCaseIds = new List<Id>();
        List<Id> parentIds = new List<Id>();
        List<Id> dataOwnerIds = new List<Id>();
        List<Case> unsubCases = new List<Case>();
        List<Case> newEmailPrivacyCases = new List<Case>();
        for (sObject sobjCase : Trigger.new) {
            Case cse = (Case)sobjCase;
            if (cse.RecordTypeId == Constants.dataOwnerCaseRecordTypeId || cse.RecordTypeId == Constants.privacyRecordTypeId) {
                privacyCases.add(cse);
            } else {
                if (
                    cse.Type == Constants.marketingCaseType &&
                    cse.Sub_Type__c == Constants.unsubscribeRequestSubType
                    ) {
                        System.debug('===adding unsub case' + cse);
                        unsubCases.add(cse);
                    }
                if (
                    cse.Type == Constants.privacyCaseType &&
                    cse.Sub_Type__c == Constants.privacyEmailSubType &&
                    cse.Status == Constants.newPrivacyStatus &&
                    Trigger.isUpdate
                    ) {
                        Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
                        if (String.isNotBlank(cse.emailToAddress__c) && String.isBlank(oldCase.emailToAddress__c)) {
                            newEmailPrivacyCases.add(cse);
                        }
                    }
                continue;
            }
            if (cse.Sub_Type__c == Constants.dataOwnerRequestSubType) {
                System.debug('===dataOwnerCase');
                if (!parentIds.contains(cse.ParentId)) {
                    parentIds.add(cse.ParentId);
                }
                if (!dataOwnerIds.contains(cse.Data_Owner__c)) {
                    System.debug('===adding Data Owner Id ' + cse.Data_Owner__c);
                    dataOwnerIds.add(cse.Data_Owner__c);
                }
            } else {
                if (Trigger.isInsert) {
                    newCaseIds.add(cse.Id);
                }
            }
        }
        if (privacyCases.size() > 0) {
            if (newCaseIds.size() > 0) {
                ContactFuture.processNewPrivacyCases(newCaseIds);
            }
            sendPrivacyEmailsIfNeeded(privacyCases, parentIds, dataOwnerIds);
            if (Trigger.isUpdate) {
                createChildCasesIfNeeded(privacyCases);
            }
        }
        if (unsubCases.size() > 0) {
            processUnsubCases(unsubCases);
        }
        if (newEmailPrivacyCases.size() > 0) {
            processNewEmailPrivacyCases(newEmailPrivacyCases);
        }
    }

    /***********************************************************************************************
    * @description Handles sending autoresponse emails to inbound emails to privacy email
    * addresses.
    * @param newCases List of new Email Privacy cases to send autoresponse emails to
    */
    private static void processNewEmailPrivacyCases(List<Case> newCases) {
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
        PrivacyEmailHandler emailHandler = new PrivacyEmailHandler();
        for (Case cse : newCases) {
            System.debug('===processing new email privacy case' + cse);
            List<Brand_Setting__mdt> brandSetting = [Select Privacy_Auto_Response_Email_Template__c From Brand_Setting__mdt Where Brand_Id__c = :cse.Brand__c];
            if (brandSetting.size() == 0) {
                continue;
            }
            
            Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, brandSetting[0].Privacy_Auto_Response_Email_Template__c, cse.SuppliedEmail);
            if (email == null) {
                System.debug('===null email' + cse);
                continue;
            }
            System.debug('===sending email' + email);
            emailsToSend.add(email);
        }
        emailHandler.sendEmails(emailsToSend);
    }

    /***********************************************************************************************
    * @description Handles sending automated emails for unsub cases.
    * Verification and Case Closed emails
    * @param unsubCases List of unsub cases to send emails for.
    */
    private static void processUnsubCases(List<Case> unsubCases) {
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
        PrivacyEmailHandler emailHandler = new PrivacyEmailHandler();
        for (Case cse : unsubCases) {
            System.debug('===processing unsub case' + cse);
            if (Trigger.isInsert && cse.Status == Constants.newPrivacyStatus) {
                Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.U1UnsubscribeEmail, cse.SuppliedEmail);
                if (email == null) {
                    continue;
                }
                emailsToSend.add(email);
            } else if (cse.Status == Constants.resolved && Trigger.isUpdate) {
                Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
                if (oldCase.status != Constants.resolved) {
                    if (cse.Resolution_Code__c == Constants.privacyResolvedNoResponse) {
                        Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.U3UnsubscribeEmail, cse.SuppliedEmail);
                        if (email == null) {
                            continue;
                        }
                        emailsToSend.add(email);
                    } else if (cse.Resolution_Code__c == Constants.privacyResolvedRejectedRequest) {
                        Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.U2UnsubscribeEmail, cse.SuppliedEmail);
                        if (email == null) {
                            continue;
                        }
                        emailsToSend.add(email);
                    }
                }
            }
        }
        emailHandler.sendEmails(emailsToSend);
    }

    /***********************************************************************************************
    * @description Determines if child cases should be created for the parent case that has
    * reached the appropriate stage. This is determined by type of case (deletion vs access) and 
    * whether the brand account has supplemental data owners. If new cases are needed, call an aync
    * method which handles that. If not, progress to the next appropriate stage.
    * @param cases parent cases to process
    */
    private static void createChildCasesIfNeeded(List<Case> cases) {
        List<Case> casesNeedingUpdate = new List<Case>();
        List<Account> accountsWithSupplementalDataOwners = [Select Name From Account Where Id In (Select AccountId From Contact Where RecordTypeId = :Constants.dataOwnerContactRecordTypeId And System_Type__c = :Constants.dataOwnerSupplemental)];
        List<String> accountNamesWithSupplemental = new List<String>();
        Map<String,String> brandValueMap = new Map<String,String>();
        List<Schema.Picklistentry> fieldResult = Case.Brand__c.getDescribe().getPicklistValues();
        for (Schema.Picklistentry ple: fieldResult) {
            brandValueMap.put(ple.getValue(), ple.getLabel());
        }
        for (Account a : accountsWithSupplementalDataOwners) {
            if (!accountNamesWithSupplemental.contains(a.Name)) {
                accountNamesWithSupplemental.add(a.Name);
            }
        }
        for(Case cse : cases) {
            Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
            System.debug('===casecreatingifneeded' + cse);
            System.debug('===oldcasecreatingifneeded' + oldCase);
            if (
                cse.Type == Constants.privacyCaseType && 
                (cse.Sub_Type__c == Constants.accessRequestSubType || cse.Sub_Type__c == Constants.deletionRequestSubType) && 
                cse.Status == Constants.dataOwnersContacted &&
                oldCase.Status != Constants.dataOwnersContacted
            ) {
                if (cse.Perfect_Match_Found__c) {
                    if (cse.Sub_Type__c == Constants.accessRequestSubType && !accountNamesWithSupplemental.contains(brandValueMap.get(cse.Brand__c))) {
                        //CSR has all data for the brand already
                        Case newCase = new Case(Id=cse.Id);
                        newCase.Status = Constants.reviewResponseStatus;
                        casesNeedingUpdate.add(newCase);
                    } else {
                        //Need to contact data owners for deletion/additional info
                        ChildPrivacyCaseActionsHandler.createChildDataOwnerCases(cse.Id);
                    }
                } else {
                    if (!Constants.privacyNACountries.contains(cse.Country_of_Residence__c)) {
                        // No Match and no NA, resolve the case.
                        Case newCase = new Case(Id=cse.Id);
                        newCase.Status = Constants.resolved;
                        newCase.Resolution_Code__c = Constants.privacyResolvedNoDataFound;
                        casesNeedingUpdate.add(newCase);
                    } else {
                        if (accountNamesWithSupplemental.contains(brandValueMap.get(cse.Brand__c))) {
                            // In NA without a match, but need to see if supplemental owners have data on consumer
                            ChildPrivacyCaseActionsHandler.createChildDataOwnerCases(cse.Id);
                        } else {
                            // In NA, but no supplemental data owners to contact. resolve it.
                            Case newCase = new Case(Id=cse.Id);
                            newCase.Status = Constants.resolved;
                            newCase.Resolution_Code__c = Constants.privacyResolvedNoDataFound;
                            casesNeedingUpdate.add(newCase);
                        }
                    }

                }
            }
        }
        if (casesNeedingUpdate.size() > 0) {
            update casesNeedingUpdate;
        }
    }

    /***********************************************************************************************
    * @description Sends automated privacy emails. Processes access, delete, and data owner cases.
    * @param cases list of cases to process
    * @param parentIds List of parent case ids for data owner cases. (To limit SOQL)
    * @param dataOwnerIds List of data owner ids (contacts) associated with data owner cases.
    */
    private static void sendPrivacyEmailsIfNeeded(List<Case> cases, List<Id> parentIds, List<Id> dataOwnerIds) {
        Map<Id, String> dataOwnerEmailMap = new Map<Id, String>();
        Map<Id, Case> parentCasesMap = new Map<Id, Case>();
        Map<Id, List<String>> dataOwnerAddtionalEmailsMap = new Map<Id, List<String>>();
        if (parentIds.size() > 0) {
            List <Case> parentCases = [Select Id, Sub_Type__c From Case Where Id In :parentIds];
            for (Case parentCase : parentCases) {
                parentCasesMap.put(parentCase.Id, parentCase);
            }
        }
        System.debug('===data Owner Ids ' + dataOwnerIds);
        if (dataOwnerIds.size() > 0) {
            System.debug('===Searching for data owners');
            List<Contact> dataOwners= [Select Id, Email, Additional_Email_1__c, Additional_Email_2__c, Additional_Email_3__c, Additional_Email_4__c From Contact Where Id In :dataOwnerIds];
            System.debug('data Owners ' + dataOwners);
            for (Contact dataOwner : dataOwners) {
                List<String> additionalEmails = new List<String>();
                if (String.isNotBlank(dataOwner.Additional_Email_1__c)) additionalEmails.add(dataOwner.Additional_Email_1__c);
                if (String.isNotBlank(dataOwner.Additional_Email_2__c)) additionalEmails.add(dataOwner.Additional_Email_2__c);
                if (String.isNotBlank(dataOwner.Additional_Email_3__c)) additionalEmails.add(dataOwner.Additional_Email_3__c);
                if (String.isNotBlank(dataOwner.Additional_Email_4__c)) additionalEmails.add(dataOwner.Additional_Email_4__c);
                dataOwnerAddtionalEmailsMap.put(dataOwner.Id, additionalEmails);
                dataOwnerEmailMap.put(dataOwner.Id, dataOwner.Email);
            }
        }
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
        PrivacyEmailHandler emailHandler = new PrivacyEmailHandler();
        for (Case cse : cases) {
            System.debug('sending emails for case maybe' + cse);
            System.debug('===case id ' + cse.Id);
            if (cse.Type != Constants.privacyCaseType ) {
                continue;
            }
            if (cse.Sub_Type__c == Constants.accessRequestSubType) {
                emailsToSend = processAccessCases(cse, emailsToSend, emailHandler);
            }
            if (cse.Sub_Type__c == Constants.dataOwnerRequestSubType && String.isNotBlank(cse.Id)) {
                emailsToSend = processDataOwnerCases(cse, emailsToSend, emailHandler, parentCasesMap, dataOwnerAddtionalEmailsMap, dataOwnerEmailMap);
            }
            if (cse.Sub_Type__c == Constants.deletionRequestSubType) {
                emailsToSend = processDeletionCase(cse, emailsToSend, emailHandler);
            }
            
        }
        if (emailsToSend.size() > 0) {
            emailHandler.sendEmails(emailsToSend);
        }
    }

    /***********************************************************************************************
    * @description Adds automated privacy access email to list of emails to be sent
    * @param cse access case to process
    * @param emailsToSend List of emails to be sent after processing all cases
    * @param emailHandler class that generates the email to send
    * @return emailsToSend with another email if one is created
    */
    private static List<Messaging.SingleEmailMessage> processAccessCases(Case cse, List<Messaging.SingleEmailMessage> emailsToSend, PrivacyEmailHandler emailHandler) {
        if (Trigger.isInsert) {
            Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.A1RequestEmail);
            if (email == null) {
                return emailsToSend;
            }
            emailsToSend.add(email);
        } else if (Trigger.isUpdate) {
            Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
            if (cse.Status == Constants.resolved && oldCase.Status != Constants.resolved) {
                System.debug('===AccessCase ' + cse.Resolution_Code__c);
                Messaging.SingleEmailMessage email;
                if (cse.Resolution_Code__c == Constants.privacyResolvedDataProvided) {
                    // NO AUTOMATED EMAIL, CSR MANUALLY SENDS
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedRejectedRequest) {
                    email = emailHandler.createEmail(cse, Constants.A2RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedNoResponse) {
                    email = emailHandler.createEmail(cse, Constants.A3RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedStalled) {
                    email = emailHandler.createEmail(cse, Constants.A10RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedNoDataFound) {
                    if (Constants.privacyNACountries.contains(cse.Country_of_Residence__c)) {
                        email = emailHandler.createEmail(cse, Constants.A7RequestEmail);
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    } else {
                        email = emailHandler.createEmail(cse, Constants.A8RequestEmail);
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    }
                }
            }
        }
        return emailsToSend;
        
    }

    /***********************************************************************************************
    * @description Adds automated privacy deletion email to list of emails to be sent
    * @param cse access case to process
    * @param emailsToSend List of emails to be sent after processing all cases
    * @param emailHandler class that generates the email to send
    * @return emailsToSend with another email if one is created
    */
    private static List<Messaging.SingleEmailMessage> processDeletionCase(Case cse, List<Messaging.SingleEmailMessage> emailsToSend, PrivacyEmailHandler emailHandler) {
        if (Trigger.isInsert) {
            Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, Constants.D1RequestEmail);
            if (email == null) {
                return emailsToSend;
            }
            emailsToSend.add(email);
        } else if (Trigger.isUpdate) {
            System.debug('===DeletionCase ' + cse.Resolution_Code__c);
            Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
            if (cse.Status == Constants.resolved && oldCase.Status != Constants.resolved) {
                Messaging.SingleEmailMessage email;
                if (cse.Resolution_Code__c == Constants.privacyResolvedDataDeleted) {
                    email = emailHandler.createEmail(cse, Constants.D4RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedRejectedRequest) {
                    email = emailHandler.createEmail(cse, Constants.D7RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedNoResponse) {
                    email = emailHandler.createEmail(cse, Constants.D8RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedStalled) {
                    email = emailHandler.createEmail(cse, Constants.D10RequestEmail);
                    if (email == null) {
                        return emailsToSend;
                    }
                    emailsToSend.add(email);
                } else if (cse.Resolution_Code__c == Constants.privacyResolvedNoDataFound) {
                    if (Constants.privacyNACountries.contains(cse.Country_of_Residence__c)) {
                        email = emailHandler.createEmail(cse, Constants.D5RequestEmail);
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    } else {
                        email = emailHandler.createEmail(cse, Constants.D9RequestEmail);
                        if (email == null) {
                            return emailsToSend;
                        }
                        emailsToSend.add(email);
                    }
                }
            }
        }
        return emailsToSend;
    }

    /***********************************************************************************************
    * @description Adds automated privacy data owner email to list of emails to be sent.
    * If case was resolved, also calls async method to check if parent case has had all
    * child cases resolved.
    * @param cse access case to process
    * @param emailsToSend List of emails to be sent after processing all cases
    * @param emailHandler class that generates the email to send
    * @param parentCasesMap map of parent id to parent case. (Bulkification)
    * @param dataOwnerAddtionalEmailsMap map of addtional data owner id to email address. (Bulkification)
    * dataOwnerEmailMap Map of data owner id to email address (Bulkification)
    * @return emailsToSend with another email if one is created
    */
    private static List<Messaging.SingleEmailMessage> processDataOwnerCases(Case cse, List<Messaging.SingleEmailMessage> emailsToSend, PrivacyEmailHandler emailHandler, Map<Id, Case> parentCasesMap, Map<Id, List<String>> dataOwnerAddtionalEmailsMap, Map<Id, String> dataOwnerEmailMap) {
        Case parentCase = parentCasesMap.get(cse.ParentId);
        if (Trigger.isInsert) {
            String emailTemplate;
            if (parentCase.Sub_Type__c == Constants.accessRequestSubType) {
                emailTemplate = Constants.A5RequestEmail;
            } else {
                emailTemplate = Constants.D3RequestEmail;
            }
            Messaging.SingleEmailMessage email = emailHandler.createEmail(cse, emailTemplate, dataOwnerEmailMap.get(cse.Data_Owner__c));
            if (email == null) {
                return emailsToSend;
            }
            List<String> additionalEmailAddresses = dataOwnerAddtionalEmailsMap.get(cse.Data_Owner__c);
            System.debug('===additional emails' + additionalEmailAddresses);
            if (additionalEmailAddresses.size() > 0) {
                email.setCcAddresses(additionalEmailAddresses);
                    
            }
            emailsToSend.add(email);
        }
        if (Trigger.isUpdate) {
            System.debug('===UPDATING DATA OWNER CASE' + cse);
            if(Constants.privacyCaseCompletedStatuses.contains(cse.Status)) {
                Case oldCase = (Case)Trigger.oldMap.get(cse.Id);
                if (!Constants.privacyCaseCompletedStatuses.contains(oldCase.Status)) {
                    ChildPrivacyCaseActionsHandler.handleChildCaseResolved(cse.Id, cse.parentId);
                }
            }
        }
        return emailsToSend;
    }
}