objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Brand_Id__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bass</fullName>
                </value>
                <value>
                    <fullName>Calvin Klein</fullName>
                    <label>Calvin Klein</label>
                </value>
                <value>
                    <fullName>Heritage Ecom</fullName>
                </value>
                <value>
                    <fullName>Izod</fullName>
                </value>
                <value>
                    <fullName>IZOD.com</fullName>
                </value>
                <value>
                    <fullName>Partner Brands</fullName>
                    <label>Partner Brands</label>
                </value>
                <value>
                    <fullName>Speedo</fullName>
                </value>
                <value>
                    <fullName>Style Bureau</fullName>
                    <label>Style Bureau</label>
                </value>
                <value>
                    <fullName>Tommy Hilfiger</fullName>
                </value>
                <value>
                    <fullName>Van Heusen</fullName>
                </value>
                <value>
                    <fullName>Van Heusen.com</fullName>
                    <label>Van Heusen.com</label>
                </value>
                <value>
                    <fullName>Warners.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <fields>
        <fullName>EmailOptInStatus__c</fullName>
        <label>Email Opt-in</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StoreOfCapture__c</fullName>
        <label>Store Of Capture</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WelcomeSource__c</fullName>
        <label>Welcome Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                    <label>1-Overlay</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>2-Footer</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>3-My Account</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>4-Guest Checkout</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GenericRecords__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>recordId__c</fullName>
        <description>Id of the generic record</description>
        <label>recordId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Generic Records</label>
</CustomObject>

globalValueSets/Brand_Id.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

classes/ContactTriggerTest.cls
@isTest
private class ContactTriggerTest {

    private static testmethod void ContactTriggerTest() {

        insert new et4ae5__Configuration__c(et4ae5__Support_Ticket_Recipient__c = 'example@example.com');
        Test.startTest();
        Contact c = new Contact(LastName='TestExample',Brand_Id__c='9');
        insert c;
        System.assert(!String.isBlank(c.Id));
        Test.stopTest();

    }

    @isTest static void TestDeleteContact() {
        // Test data setup
        Account acc = new Account();
        acc.Name = 'generic Account' + Math.random();
        insert acc;

        Contact con = new Contact();
        con.email = 'foo@example.com';
        con.lastName = 'generic contact ' + Math.random();
        con.AccountId = acc.id;
        con.Brand_Id__c='9';
        insert con;

        GenericRecords__c genRec = new GenericRecords__c(
                Name = Constants.privacyContactGenericRecordSettingName,
                recordId__c = con.Id
        );
        insert genRec;

        GenericRecords__c genRecAcct = new GenericRecords__c(
                Name = Constants.AccountGenericRecordSettingName,
                recordId__c = acc.Id
        );
        insert genRecAcct;

        Account acct = new Account(
                Name='Test Account ' + Math.random()
        );
        insert acct;
        Contact cont = new Contact(
                LastName='contact ' + Math.random(),
                AccountId=acct.Id,Brand_Id__c='9',
                RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId()
        );
        insert cont;
        Asset a = new Asset(
                ContactId=cont.Id,
                Name='Asset ' + Math.random()
        );
        insert a;
        Case c = new Case(
                ContactId=cont.Id,
                AccountId=acct.Id,
                Origin='Chat',
                Brand__c='2',
                Status='Open',
                RecordTypeId=Constants.supportCaseRecordTypeId,
                AssetId=a.Id
        );
        insert c;
        Contract ct = new Contract(
                CustomerSignedId=cont.Id,
                AccountId=acct.Id
        );
        insert ct;

        // Perform test
        Test.startTest();
        Database.DeleteResult result = Database.delete(cont, false);
        Test.stopTest();
        
        System.assert(result.isSuccess());
    }
    @isTest
    public static void upsertChildContactOnParentupdateTest(){
        Test.startTest();
        Account acct = new Account(Name='Test Account ' + Math.random());
        insert acct;
        Contact cont = new Contact(LastName='contact ' + Math.random(),AccountId=acct.Id,Brand_Id__c='9',
                RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId());
        insert cont;
        cont.EmailOptInStatus__c = 'N';
        update cont;
        cont.EmailOptInStatus__c = 'Y';
        update cont;
        Test.stopTest();
    }
    @istest
    public static void emailPreferenceTest(){
        Test.startTest();
        Account acct = new Account(Name='Test Account ' + Math.random());
        insert acct;
        Contact cont = new Contact(LastName='contact ' + Math.random(),AccountId=acct.Id,Brand_Id__c='2',
                                   StoreOfCapture__c='CK601',WelcomeSource__c='02',
                                   RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId());
        insert cont;
        
        Test.stopTest();
    }
    @isTest
    public static void accountAssociationtest(){
        Test.startTest();
		Id recid = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId(); 
        Account acct = new Account(Name='Test Account ' + Math.random());
        insert acct;
        Contact cont = new Contact(LastName='contact ' + Math.random(),AccountId=acct.Id,Brand_Id__c='9',
                                   StoreOfCapture__c='601',WelcomeSource__c='02',Email= 'ex@test.com',
                                   RecordTypeId=recid,Status__c ='ACTIVE');

        insert cont;
        List<COntact> cntlist = new List<Contact>();
		Contact cnt = new Contact(FirstName = 'Child',LastName ='Brand84',Email ='ex@test.com',
                                  Brand_Id__c='84',Status__c ='ACTIVE');
		Contact cnt1 = new Contact(FirstName = 'Parent',LastName ='Brand4',Email ='ex@test.com',
                                   Brand_Id__c='4',Status__c ='ACTIVE');
		Contact cnt2 = new Contact(FirstName = 'Parent',LastName ='Bramd3',Email ='exp@ex.com',
                                  Brand_Id__c='1',Status__c ='ACTIVE');
		cntlist.add(cnt2);
		cntlist.add(cnt);
		cntlist.add(cnt1);
		insert cntlist;
        
        Test.stopTest();
    }
}