objects/Brand_Name_Setting__mdt.object
<CustomObject>
    <description>This custom metadata is created for mapping of Brand Name and Brand Label.  Use it where we want Brand Label corresponding to Brand Name</description>
    <fields>
        <fullName>Brand_Label__c</fullName>
        <label>Brand Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Name__c</fullName>
        <label>Brand Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Brand Name Setting</label>
    <pluralLabel>Brand Name Settings</pluralLabel>
</CustomObject>

objects/Brand_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Brand_Email__c</fullName>
        <label>Brand Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Id__c</fullName>
        <label>Brand Id</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Brand_Phone__c</fullName>
        <label>Brand Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Personal_Info_Link__c</fullName>
        <label>Personal Info Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Privacy_Email__c</fullName>
        <label>Privacy Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Privacy_Policy__c</fullName>
        <label>Privacy Policy</label>
        <type>Url</type>
    </fields>
    <label>Brand Setting</label>
    <pluralLabel>Brand Settings</pluralLabel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand_Label__c</fullName>
        <label>Brand Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <description>This field is used to show Country in Personal Data Request Form</description>
        <inlineHelpText>Need to Select the Country of Residence</inlineHelpText>
        <label>Country of Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>United States of America (USA)</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia &amp; Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Availability Questions</fullName>
                </value>
                <value>
                    <fullName>Quality Concerns</fullName>
                </value>
                <value>
                    <fullName>Sizing Questions</fullName>
                </value>
                <value>
                    <fullName>Care Instructions</fullName>
                </value>
                <value>
                    <fullName>Product Feedback</fullName>
                </value>
                <value>
                    <fullName>Problem Placing Order</fullName>
                </value>
                <value>
                    <fullName>Tracking Order Shipment</fullName>
                </value>
                <value>
                    <fullName>Edit Existing Order</fullName>
                </value>
                <value>
                    <fullName>Cancel Order</fullName>
                </value>
                <value>
                    <fullName>Missing/Damaged Product</fullName>
                </value>
                <value>
                    <fullName>Return Policy</fullName>
                </value>
                <value>
                    <fullName>Returning Order</fullName>
                </value>
                <value>
                    <fullName>Creating Return Label</fullName>
                </value>
                <value>
                    <fullName>Tracking Return</fullName>
                </value>
                <value>
                    <fullName>Return Status</fullName>
                </value>
                <value>
                    <fullName>Signing Up</fullName>
                </value>
                <value>
                    <fullName>Program Questions</fullName>
                </value>
                <value>
                    <fullName>Adding Points</fullName>
                </value>
                <value>
                    <fullName>Redeeming Rewards</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Update Information</fullName>
                </value>
                <value>
                    <fullName>Problem Receiving</fullName>
                </value>
                <value>
                    <fullName>Unsubscribe</fullName>
                </value>
                <value>
                    <fullName>Access My Data</fullName>
                </value>
                <value>
                    <fullName>Delete My Data</fullName>
                </value>
                <value>
                    <fullName>Data Owner Request</fullName>
                </value>
                <value>
                    <fullName>Privacy Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Privacy_Request</fullName>
        <active>true</active>
        <businessProcess>Privacy Request</businessProcess>
        <label>Privacy Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>Support_Case</fullName>
        <active>true</active>
        <businessProcess>Support Case</businessProcess>
        <label>Support Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Brand_Id__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Personal_Data_Request_Setting__mdt.object
<CustomObject>
    <description>This custom metadata is used to store values for field "Type of Request"</description>
    <fields>
        <fullName>Brand_Name__c</fullName>
        <label>Brand Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>calvinklein</fullName>
                    <default>true</default>
                    <label>calvinklein</label>
                </value>
                <value>
                    <fullName>izod</fullName>
                </value>
                <value>
                    <fullName>olga</fullName>
                </value>
                <value>
                    <fullName>pvh</fullName>
                </value>
                <value>
                    <fullName>speedo</fullName>
                </value>
                <value>
                    <fullName>tommy</fullName>
                </value>
                <value>
                    <fullName>trueandco</fullName>
                </value>
                <value>
                    <fullName>vanheusen</fullName>
                </value>
                <value>
                    <fullName>warners</fullName>
                </value>
                <value>
                    <fullName>stylebureau</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Request__c</fullName>
        <description>This custom field is used to store the "Type of Request" values</description>
        <label>Type of Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Unsubscribe</fullName>
                    <default>true</default>
                    <label>Unsubscribe</label>
                </value>
                <value>
                    <fullName>Access My Data</fullName>
                </value>
                <value>
                    <fullName>Delete My Data</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Personal Data Request Setting</label>
    <pluralLabel>Personal Data Requests Settings</pluralLabel>
</CustomObject>

objects/Success_Message_Setting__mdt.object
<CustomObject>
    <description>This custom metadata is used to configure success message based on specific brand for Brand Forms.
Please provide the custom success message and put &lt;ticketid&gt; where ever you need to keep Ticket Number</description>
    <fields>
        <fullName>Brand_Email__c</fullName>
        <label>Brand Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Name__c</fullName>
        <description>This field is used to store Name of Brand</description>
        <label>Brand Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>This field is used to story Case Source Country</description>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regards__c</fullName>
        <label>Regards</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Success_Message_f__c</fullName>
        <label>Success Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field is used to store type of form</description>
        <inlineHelpText>Represents either Privacy or Brand Form</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Request__c</fullName>
        <label>Type of Request</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Success Message Setting</label>
    <pluralLabel>Success Message Settings</pluralLabel>
</CustomObject>

globalValueSets/Brand_Id.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

classes/PersonalDataFormApexController.cls
/**
* @author Magnet360
*
* @date 2019
*
* @description Controller Class to show picklist values to Privacy Data Form and
*				 to create Case after form submission.
*/
public class PersonalDataFormApexController
{

    /*******************************************************************************************************
    * @description Method to fetch below field Values from Case Object and show it to Privacy Data Forms:
    * Country of Residence
    * State of Residence
    * Type of Request (Custom Metadata - Personal Data Request Setting)
    * @param objDetail - Case record as SObject
    * @param contrfieldApiName  - API name of Controlling Field
    * @param depfieldApiName - API Name of Dependent FIeld
    * @param brandNames -Brand Name
    * @param sourceCountry - Country US or CA
    * @return InitialDataWrapper
    */
    @AuraEnabled  
    public static InitialDataWrapper getDependentMap(sObject objDetail, string contrfieldApiName,string depfieldApiName,String brandNames,String sourceCountry) {
        InitialDataWrapper wrapperObj = new InitialDataWrapper();
        
        
        String controllingField = contrfieldApiName.toLowerCase();
        String dependentField = depfieldApiName.toLowerCase();
        
        Map<String,List<String>> objResults = new Map<String,List<String>>();
        
        Schema.sObjectType objType = objDetail.getSObjectType();
        if (objType==null){
            
            wrapperObj.mapCountryState = objResults;
        	return wrapperObj;
        	
        }
        
        Map<String, Schema.SObjectField> objFieldMap = objType.getDescribe().fields.getMap();
        
        if (!objFieldMap.containsKey(controllingField) || !objFieldMap.containsKey(dependentField)){
           wrapperObj.mapCountryState = objResults;
           return wrapperObj;
         
        }
        
        Schema.SObjectField theField = objFieldMap.get(dependentField);
        Schema.SObjectField ctrlField = objFieldMap.get(controllingField);
        
        List<Schema.PicklistEntry> contrEntries = ctrlField.getDescribe().getPicklistValues();
        //System.debug('***Controlling = '+contrEntries);
        List<PicklistEntryWrapper> depEntries = wrapPicklistEntries(theField.getDescribe().getPicklistValues());
        //System.debug('***Dependent = '+depEntries);
        List<String> controllingValues = new List<String>();
        
        for (Schema.PicklistEntry ple : contrEntries) {
            String label = ple.getLabel();
            objResults.put(label, new List<String>());
            controllingValues.add(label);
        }
        
        for (PicklistEntryWrapper plew : depEntries) {
            String label = plew.label;
            String validForBits = base64ToBits(plew.validFor);
            for (Integer i = 0; i < validForBits.length(); i++) {
                String bit = validForBits.mid(i, 1);
                if (bit == '1') {
                    objResults.get(controllingValues.get(i)).add(label);
                }
            }
        }
        //System.debug('***Final Map = '+objResults);
        wrapperObj.mapCountryState = objResults;
        //System.debug('***Wrapper Obj = '+wrapperObj.mapCountryState);
        
        //Fetching Picklist values for field "Type of Request" from Custom Metadata.
        List<String> listType = new List<String>();
        // List<String> listBrands = new List<String>();
        Schema.sObjectType objTypeCase = Personal_Data_Request_Setting__mdt.getSObjectType();
        Schema.DescribeSObjectResult objDescribe = objTypeCase.getDescribe();
        
        map <String, Schema.SObjectField> typeMap = objDescribe.fields.getMap();
        list <Schema.PicklistEntry> values = typeMap.get('Type_of_Request__c').getDescribe().getPickListValues();
        for (Schema.PicklistEntry a: values) 
        {
            listType.add(a.getValue());
        }
        //System.debug('***Got Type = '+listType);
        String brandLabel = (sourceCountry == 'US')?brandNames:brandNames+' '+sourceCountry;
        system.debug('*** brandLabel '+brandLabel);
        //List<Success_Message_Setting__mdt> getMessage = [Select Id,Success_Message_f__c,Regards__c,	MasterLabel,Brand_Email__c from Success_Message_Setting__mdt Where Type__c='P' and Brand_Name__c=:brandNames and Country__c=:sourceCountry];
        List<Brand_Setting__mdt> getMessage = [Select Id, Privacy_Email__c, Brand_Phone__c, Privacy_Policy__c, Personal_Info_Link__c, MasterLabel from Brand_Setting__mdt where Brand_Id__c = :brandLabel];
        if(!getMessage.isEmpty())
        {
            //System.debug('$$$'+getMessage[0].MasterLabel);
            //System.debug('$$$'+getMessage[0].Brand_Email__c);
            //System.debug('***Got Configurd Message');
            wrapperObj.brand_label = getMessage[0].MasterLabel;
            wrapperObj.brand_email = getMessage[0].Privacy_Email__c;
            wrapperObj.brand_phone = getMessage[0].Brand_Phone__c;
            wrapperObj.brand_privacyPolicy = getMessage[0].Privacy_Policy__c;
            wrapperObj.brand_optOutInfo = getMessage[0].Personal_Info_Link__c;
        }

        wrapperObj.listTypeOfRequest = listType;
        system.debug('*** wrapperObj '+wrapperObj);
        return wrapperObj;
    }
    
    public static String decimalToBinary(Integer val) {
        String bits = '';
        while (val > 0) {
            Integer remainder = Math.mod(val, 2);
            val = Integer.valueOf(Math.floor(val / 2));
            bits = String.valueOf(remainder) + bits;
        }
        return bits;
    }
    
    public static String base64ToBits(String validFor) {
        if (String.isEmpty(validFor)) return '';
        
        String validForBits = '';
        
        for (Integer i = 0; i < validFor.length(); i++) {
            String thisChar = validFor.mid(i, 1);
            Integer val = base64Chars.indexOf(thisChar);
            String bits = decimalToBinary(val).leftPad(6, '0');
            validForBits += bits;
        }
        
        return validForBits;
    }
    
    private static final String base64Chars = '' +
        'ABCDEFGHIJKLMNOPQRSTUVWXYZ' +
        'abcdefghijklmnopqrstuvwxyz' +
        '0123456789+/';
    
    
    private static List<PicklistEntryWrapper> wrapPicklistEntries(List<Schema.PicklistEntry> PLEs) {
        return (List<PicklistEntryWrapper>)
            JSON.deserialize(JSON.serialize(PLEs), List<PicklistEntryWrapper>.class);
    }
    
    public class PicklistEntryWrapper{
        public String active {get;set;}
        public String defaultValue {get;set;}
        public String label {get;set;}
        public String value {get;set;}
        public String validFor {get;set;}
        public PicklistEntryWrapper(){            
        }
        
    }
    
    public class InitialDataWrapper
    {   
        @AuraEnabled
        public Map<String, List<String>> mapCountryState {get;set;}
        @AuraEnabled
        public List<String> listTypeOfRequest {get;set;}
       
        @AuraEnabled
        public String brand_label {get;set;}
        @AuraEnabled
        public String brand_email {get;set;}
        @AuraEnabled
        public String brand_phone {get;set;}
        @AuraEnabled
        public String brand_optOutInfo {get;set;}
        @AuraEnabled
        public String brand_privacyPolicy {get;set;}

    }
    
    /* Method to create Case in Salesforce when Privacy Form is submitted and return:
     * WrapperObject with:
     * CaseNumber and 
     * Success Message (Custom Metadata - Success Message Setting)
     * Regards (Custom Metadata - Success Message Setting)
     */
    /*******************************************************************************************************
    * @description Method to create Case in Salesforce when Privacy Form is submitted and return:
    * WrapperObject with:
    * CaseNumber and
    * Success Message (Custom Metadata - Success Message Setting)
    * Regards (Custom Metadata - Success Message Setting)
    * @param getCaseDetail - Case record as SObject
    * @param name - Name of Customer
    * @param brandNames - Brand name
    * @param sourceCountry - Source Country US/CA
    * @return CaseWrapper -
    */
    @AuraEnabled
    public static CaseWrapper createCase(Case getCaseDetail,String name,String brandNames,String sourceCountry)
    {
        //System.debug('***inside createCase');
        CaseWrapper wrapperObj = new CaseWrapper();
        
        Id recordTypeIdPrivacyRequest = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Privacy_Request').getRecordTypeId();
        Id recordTypeIdSupportCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();
		String typeToSet;
        String subTypeToSet;
        String recordTyeToSet;
        Map<String,String> mapBrandNameLabel = new Map<String,String>();
        
        if(getCaseDetail.Type == 'Access My Data' || getCaseDetail.Type == 'Delete My Data')
        {
            //System.debug('***its Privacy');
            typeToSet = 'Privacy';
            subTypeToSet = getCaseDetail.Type;
            recordTyeToSet = recordTypeIdPrivacyRequest;
        }
        else if(getCaseDetail.Type == 'Unsubscribe')
        {
            //System.debug('***its Marketing');
            typeToSet = 'Marketing';
            subTypeToSet = getCaseDetail.Type;
            recordTyeToSet = recordTypeIdSupportCase;
            
        }
        //System.debug('***We got Brand Name = '+brandNames);
        
        
        //fetch brand name and brand label from custom setting to a map
        List<Brand_Name_Setting__mdt> listBrandNameLabel = [SELECT Id,Brand_Name__c,Brand_Label__c FROM Brand_Name_Setting__mdt];
        if(!listBrandNameLabel.isEmpty())
        {
        	for(Brand_Name_Setting__mdt singleRec : listBrandNameLabel)
            {
                mapBrandNameLabel.put(singleRec.Brand_Name__c,singleRec.Brand_Label__c);
            }
        }
        
        
        //call method to get API name of Brand:
        //String getAPINameBrand = getBrandAPIName(brandNames);
        //System.debug('***We got BrandAPIName = '+getAPINameBrand);
        Case newCases = new Case(Type=typeToSet, 
                                 Sub_Type__c=subTypeToSet, 
                                 Country_of_Residence__c=getCaseDetail.Country_of_Residence__c, 
                                 State_of_Residence__c=getCaseDetail.State_of_Residence__c,
                                 SuppliedName=name, SuppliedEmail=getCaseDetail.SuppliedEmail, 
                                 SuppliedPhone=getCaseDetail.SuppliedPhone,
                                 Loyalty_Account_Number__c=getCaseDetail.Loyalty_Account_Number__c,
                                 Brand__c = brandNames,
                                 Origin = 'Web',
                                 recordTypeId =recordTyeToSet,
                                 Brand_Label__c = mapBrandNameLabel.get(brandNames)
                                 );

        
        try {
            insert newCases;
        } catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        
        Case getCase = [Select Id,caseNumber from Case where Id =: newCases.Id];
        //System.debug('***Case inserted with Case Number = '+getCase.CaseNumber);
        List<Success_Message_Setting__mdt> getMessage = [Select Id,Success_Message_f__c,Regards__c from Success_Message_Setting__mdt Where Type__c='P' and Brand_Name__c=:brandNames and Type_of_Request__c=:getCaseDetail.Type and Country__c=:sourceCountry];
        if(!getMessage.isEmpty())
        {
            //System.debug('***Got Configurd Message');
            wrapperObj.message_success = getMessage[0].Success_Message_f__c;
            wrapperObj.regards_success = getMessage[0].Regards__c;
        }
        else
        {
             //System.debug('***No Configurd Message. Default Message is Set');
             wrapperObj.message_success='Thank you for submitting a Personal Data Request. Your case number is <b><ticketid></b>. We will contact you before we begin to process your request.';
             wrapperObj.regards_success='Support Team';
        }
        
        
        wrapperObj.caseNumber = getCase.CaseNumber;
        return wrapperObj;

      
    }
    
    /* NOT using this method 
    public static String getBrandAPIName(String brandNames)
    {
        Map<String,String> mapBrandLabelValue = new Map<String,String>();
        Schema.sObjectType objTypeCase = Case.getSObjectType();
        Schema.DescribeSObjectResult objDescribe = objTypeCase.getDescribe();
        map <String, Schema.SObjectField> typeMap = objDescribe.fields.getMap();
        list <Schema.PicklistEntry> brandValues = typeMap.get('Brand__c').getDescribe().getPickListValues();
        for (Schema.PicklistEntry ent: brandValues) 
        {
            mapBrandLabelValue.put(ent.getLabel(),ent.getValue());
        }
        //System.debug('***We got BrandMap = '+mapBrandLabelValue);
        String brandAPIName = mapBrandLabelValue.get(brandNames);
        return brandAPIName;
    }
    */
    
    public class CaseWrapper
    { 
        @AuraEnabled
        public String caseNumber {get;set;}
        @AuraEnabled
        public String message_success {get;set;}
        @AuraEnabled
        public String regards_success {get;set;}
       
    }

}