objects/CallDetail__c.object
<CustomObject>
    <fields>
        <fullName>CallDirection__c</fullName>
        <description>CallDirection</description>
        <label>CallDirection</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallDurationInSeconds__c</fullName>
        <description>CallDurationInSeconds</description>
        <label>CallDurationInSeconds</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CallEndTime__c</fullName>
        <description>CallEndTime</description>
        <label>CallEndTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CallStartTime__c</fullName>
        <description>CallStartTime</description>
        <label>CallStartTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CallDetails</relationshipLabel>
        <relationshipName>CallDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberDialed__c</fullName>
        <description>Number dialed</description>
        <label>NumberDialed</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SkillName__c</fullName>
        <label>SkillName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CallDetail</label>
    <nameField>
        <label>CallDetail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CallDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CallDirection__c</fullName>
        <description>Call Direction</description>
        <label>CallDirection</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CallDurationInSeconds__c</fullName>
        <description>Call duration in seconds</description>
        <label>CallDurationInSeconds</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CallEndTime__c</fullName>
        <label>CallEndTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CallStartTime__c</fullName>
        <description>Call start time</description>
        <label>CallStartTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Brand__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CalvinKlein.us</fullName>
                    <label>Online - CalvinKlein.com</label>
                </value>
                <value>
                    <fullName>Calvin Klein Retail</fullName>
                    <label>Calvin Klein Store</label>
                </value>
                <value>
                    <fullName>Tommy.com</fullName>
                    <label>Online - Tommy.com</label>
                </value>
                <value>
                    <fullName>Tommy Hilfiger Retail</fullName>
                    <label>Tommy Hilfiger Store</label>
                </value>
                <value>
                    <fullName>SpeedoUSA.com</fullName>
                    <label>Online - speedo.com</label>
                </value>
                <value>
                    <fullName>Other Retailer</fullName>
                </value>
                <value>
                    <fullName>VanHeusen.com</fullName>
                    <label>Online - vanheusen.com</label>
                </value>
                <value>
                    <fullName>Van Heusen Retail</fullName>
                    <label>Van Heusen Store</label>
                </value>
                <value>
                    <fullName>Izod.com</fullName>
                    <label>Online - Izod.com</label>
                </value>
                <value>
                    <fullName>styleBureau.com</fullName>
                    <label>Online - styleBureau.com</label>
                </value>
                <value>
                    <fullName>trueandco.com</fullName>
                    <label>Online -True&amp;co.com</label>
                </value>
                <value>
                    <fullName>CalvinKlein.ca</fullName>
                    <label>Online-CalvinKlein Canada</label>
                </value>
                <value>
                    <fullName>Speedo.com</fullName>
                </value>
                <value>
                    <fullName>Warner.com</fullName>
                    <label>Online-Warner's</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Call Notes/Comments</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NumberDialed__c</fullName>
        <description>Number Dialed</description>
        <label>NumberDialed</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>SkillName__c</fullName>
        <label>SkillName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CallDetailsTriggerHandler.cls
/**
* @author Magnet360
*
* @date 2019
*
* @description Trigger Handler for CallDetails__c. After a call has been placed, RingCentral updates the Case with fields
* populated from the call. A process builder is than run to copy those values from case to a new CallDetail.
* Once the call detail has been created, the details are wiped from case to accept values from anothercase
*
*/
public class CallDetailsTriggerHandler {
    
    public static boolean RUN_ONCE = true;

    /*******************************************************************************************************
    * @description Wipes call details from the case after the call detail was created
    * @param newCallDetails - Trigger.New values from the CallDetails trigger
    * @return void
    */
    public static void clearCallDetailsOnCase(List<CallDetail__c> newCallDetails){
        System.debug('CallDetailsTriggerHandler->entered clearCallDetailsOnCase method');
        List<Id> caseIds = new List<Id>();
        for(CallDetail__c callDetail:newCallDetails){
            caseIds.add(callDetail.case__c);//capture parent case id's
        }
        System.debug('Parent case ids found '+caseIds);
        List<Case> parentCases =   [select id,CallDirection__c,CallDurationInSeconds__c,CallEndTime__c,CallStartTime__c,Comments__c,
      									SkillName__c, NumberDialed__c,Channel__c  from Case where id in :  caseIds];
        
        for(Case parentCase:parentCases){ //clear call details
            parentCase.CallDirection__c = null;
            parentCase.CallDurationInSeconds__c = null;
            parentCase.CallEndTime__c = null;
            parentCase.CallStartTime__c = null;
            parentCase.Comments__c = null;
            parentCase.SkillName__c = null;
            parentCase.NumberDialed__c = null;
        }
        //update parent cases after call details cleared
        update parentCases;
    }

}