objects/Case.object
<CustomObject>
    <fields>
        <fullName>Additional_Privacy_Request_Information__c</fullName>
        <description>This field will contain additional information to send to the Data Owners to process data owner requests</description>
        <inlineHelpText>This field will contain additional information to send to the Data Owners to process data owner requests</inlineHelpText>
        <label>Additional Privacy Request Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <description>This field is used to show Country in Personal Data Request Form</description>
        <inlineHelpText>Need to Select the Country of Residence</inlineHelpText>
        <label>Country of Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>United States of America (USA)</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia &amp; Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Data Owner's Contact Record</description>
        <label>Data Owner</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Privacy Requests</relationshipLabel>
        <relationshipName>PrivacyRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Loyalty_Account_Number__c</fullName>
        <label>Loyalty Account Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originating_Queue_Id__c</fullName>
        <label>Originating Queue Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Perfect_Match_Found__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether a Perfect Match was found for the privacy request</description>
        <label>Perfect Match Found</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Rejected Request</fullName>
                </value>
                <value>
                    <fullName>No Response to follow-up</fullName>
                </value>
                <value>
                    <fullName>Data Not Found</fullName>
                </value>
                <value>
                    <fullName>User Data Provided</fullName>
                </value>
                <value>
                    <fullName>User Data Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_of_Residence__c</fullName>
        <description>This Field is used to Show States in Personal Data Form</description>
        <inlineHelpText>Need to Select the State of Residence</inlineHelpText>
        <label>State of Residence</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country_of_Residence__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Availability Questions</fullName>
                </value>
                <value>
                    <fullName>Quality Concerns</fullName>
                </value>
                <value>
                    <fullName>Sizing Questions</fullName>
                </value>
                <value>
                    <fullName>Care Instructions</fullName>
                </value>
                <value>
                    <fullName>Product Feedback</fullName>
                </value>
                <value>
                    <fullName>Problem Placing Order</fullName>
                </value>
                <value>
                    <fullName>Tracking Order Shipment</fullName>
                </value>
                <value>
                    <fullName>Edit Existing Order</fullName>
                </value>
                <value>
                    <fullName>Cancel Order</fullName>
                </value>
                <value>
                    <fullName>Missing/Damaged Product</fullName>
                </value>
                <value>
                    <fullName>Return Policy</fullName>
                </value>
                <value>
                    <fullName>Returning Order</fullName>
                </value>
                <value>
                    <fullName>Creating Return Label</fullName>
                </value>
                <value>
                    <fullName>Tracking Return</fullName>
                </value>
                <value>
                    <fullName>Return Status</fullName>
                </value>
                <value>
                    <fullName>Signing Up</fullName>
                </value>
                <value>
                    <fullName>Program Questions</fullName>
                </value>
                <value>
                    <fullName>Adding Points</fullName>
                </value>
                <value>
                    <fullName>Redeeming Rewards</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Update Information</fullName>
                </value>
                <value>
                    <fullName>Problem Receiving</fullName>
                </value>
                <value>
                    <fullName>Unsubscribe</fullName>
                </value>
                <value>
                    <fullName>Access My Data</fullName>
                </value>
                <value>
                    <fullName>Delete My Data</fullName>
                </value>
                <value>
                    <fullName>Data Owner Request</fullName>
                </value>
                <value>
                    <fullName>Privacy Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bass</fullName>
                </value>
                <value>
                    <fullName>Calvin Klein</fullName>
                    <label>Calvin Klein</label>
                </value>
                <value>
                    <fullName>Heritage Ecom</fullName>
                </value>
                <value>
                    <fullName>Izod</fullName>
                </value>
                <value>
                    <fullName>IZOD.com</fullName>
                </value>
                <value>
                    <fullName>Partner Brands</fullName>
                    <label>Partner Brands</label>
                </value>
                <value>
                    <fullName>Speedo</fullName>
                </value>
                <value>
                    <fullName>Style Bureau</fullName>
                    <label>Style Bureau</label>
                </value>
                <value>
                    <fullName>Tommy Hilfiger</fullName>
                </value>
                <value>
                    <fullName>Van Heusen</fullName>
                </value>
                <value>
                    <fullName>Van Heusen.com</fullName>
                    <label>Van Heusen.com</label>
                </value>
                <value>
                    <fullName>Warners.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <fields>
        <fullName>System_Type__c</fullName>
        <description>The type of system for which the Data Owner is Responsible</description>
        <label>System Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
                <value>
                    <fullName>External - Managed By PVH</fullName>
                </value>
                <value>
                    <fullName>Supplemental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Brand_Id.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

classes/ChildPrivacyCaseActionsHandler.cls
/**
* @author Magnet360
* @date 2019
*
* @group Case
* @group-content ../../ApexDocContent/Case.htm
*
* @description Handles asynchronous actions that interact with data owner cases
* for CCPA workflow.
*/
public class ChildPrivacyCaseActionsHandler {

    /***********************************************************************************************
    * @description Creates child Data Owner cases for a CCPA request. Asynchronous
    * @param caseId Id of the parent case which is triggering the child cases
    */
    @future
    public static void createChildDataOwnerCases(Id caseId) {
        Case cse = [Select Id, Type, OwnerId, AccountId, Brand__c, ContactId, SuppliedEmail, SuppliedName, SuppliedPhone, Origin, Country_of_Residence__c, State_of_Residence__c, Sub_Type__c, Additional_Privacy_Request_Information__c, Perfect_Match_Found__c, Due_Date__c, Loyalty_Account_Number__c From Case Where Id = :caseId];

        Map<String,String> brandValueMap = new Map<String,String>();
        List<Schema.Picklistentry> fieldResult = Case.Brand__c.getDescribe().getPicklistValues();
        for (Schema.Picklistentry ple: fieldResult) {
            brandValueMap.put(ple.getValue(), ple.getLabel());
        }
        String brandName = brandValueMap.get(cse.Brand__c);
        List<Contact> dataOwners;
        if (cse.Sub_Type__c == Constants.accessRequestSubType) {
            dataOwners = [Select Id, Email From Contact Where AccountId  In (Select Id From Account Where Name = :brandName) and System_Type__c = :Constants.dataOwnerSupplemental and RecordTypeId = :Constants.dataOwnerContactRecordTypeId];
        } else {
            if (cse.Perfect_Match_Found__c) {
                dataOwners = [Select Id, Email From Contact Where AccountId  In (Select Id From Account Where Name = :brandName) and RecordTypeId = :Constants.dataOwnerContactRecordTypeId];
            } else {
                dataOwners = [Select Id, Email From Contact Where AccountId  In (Select Id From Account Where Name = :brandName) and RecordTypeId = :Constants.dataOwnerContactRecordTypeId and System_Type__c = :Constants.dataOwnerSupplemental];
            }
             
        }

        List<Case> newCases = new List<Case>();
        for (Contact dataOwner : dataOwners) {
            Case newCase = cse.clone();
            newCase.Sub_Type__c = Constants.dataOwnerRequestSubType;
            newCase.Status = Constants.waitingForResponse;
            newCase.Data_Owner__c = dataOwner.Id;
            newCase.ParentId = cse.Id;
            newCase.RecordTypeId = Constants.dataOwnerCaseRecordTypeId;
            System.debug('===newcase '+ newCase);
            newCases.add(newCase);
        }
        insert newCases;
    }

    /***********************************************************************************************
    * @description Called when data owner case is resolved.
    * Moves attachments to parent. Resolves parent case if this was the last open child case. 
    * Asynchronous
    * @param parentId Id of the parent case 
    * @param caseId Id of the child case which was just resolved
    */
    @future
    public static void handleChildCaseResolved(Id caseId, Id parentId) {
        addAttachmentsToParent(caseId, parentId);
        updateParentCaseIfAllChildrenClosed(parentId);
    }

    /***********************************************************************************************
    * @description Adds attachments from inbound emails to the parent case.
    * @param parentId Id of the parent case 
    * @param caseId Id of the child case which was just resolved
    */
    public static void addAttachmentsToParent(Id caseId, Id parentId) {
        List<EmailMessage> messagesWithAttachments = [Select Id From EmailMessage Where ParentId = :caseId And Incoming=True And HasAttachment=True];
        if (messagesWithAttachments.size() > 0) {
            List<Id> messageIds = new List<Id>();
            for (EmailMessage message : messagesWithAttachments) {
                messageIds.add(message.Id);
            }
            List<ContentDocumentLink> oldLinks = [Select Id, ContentDocumentId, LinkedEntityId, ShareType, Visibility From ContentDocumentLink Where LinkedEntityId In :messageIds];
            List<ContentDocumentLink> newLinks = new List<ContentDocumentLink>();
            for (ContentDocumentLink oldLink :oldLinks) {
                ContentDocumentLink newLink = oldLink.clone();
                newLink.LinkedEntityId = parentId;
                newLinks.add(newLink);
            }
            System.debug('===new links' + newLinks);
            insert newLinks;
        }
    }

    /***********************************************************************************************
    * @description Resolves parent case if all children are resolved
    * @param caseId Id of the parent case
    */
    public static void updateParentCaseIfAllChildrenClosed(Id caseId) {
        List<Case> omniCases = new List<Case>();

        Integer openChildren = [Select Count() From Case Where ParentId = :caseId And Status Not In :Constants.privacyCaseCompletedStatuses];
        System.debug('open children' + openChildren);
        if (openChildren == 0) {
            Case parentCase = [Select Id,ParentId,RecordTypeId, Sub_Type__c, Status, Perfect_Match_Found__c, Originating_Queue_Id__c, State_of_Residence__c From Case Where Id = :caseId];
            if (parentCase.Status != Constants.resolved && !Constants.privacyCaseCompletedStatuses.contains(parentCase.Status)) {
                System.debug('===status good' + parentCase);
                parentCase.Status = Constants.resolved;
                if (parentCase.Sub_Type__c == Constants.deletionRequestSubType) {
                    if (parentCase.Perfect_Match_Found__c) {
                        parentCase.Resolution_Code__c = Constants.privacyResolvedDataDeleted;
                    } else {
                        Integer childDeletionsCount = [Select Count() From Case Where ParentId = :caseId And Resolution_Code__c = :Constants.privacyResolvedDataDeleted];
                        if ( childDeletionsCount == 0) {
                            parentCase.Resolution_Code__c = Constants.privacyResolvedNoDataFound;
                        } else {
                            parentCase.Resolution_Code__c = Constants.privacyResolvedDataDeleted;
                        }
                    }
                    
                } else if (parentCase.Sub_Type__c == Constants.accessRequestSubType) {
                    if (parentCase.Perfect_Match_Found__c) {
                        parentCase.Status = Constants.reviewResponseStatus;
                        omniCases.add(parentCase);
                    } else {
                        Integer childProvidedCount = [Select Count() From Case Where ParentId = :caseId And Resolution_Code__c = :Constants.privacyResolvedDataProvided];
                        if ( childProvidedCount == 0) {
                            parentCase.Resolution_Code__c = Constants.privacyResolvedNoDataFound;
                        } else {
                            parentCase.Status = Constants.reviewResponseStatus;
                            omniCases.add(parentCase);
                        }
                    }
                }
                if (omniCases.size() > 0) {
                    PrivacyCaseQueueHandler.sendCasesToOmni(omniCases);
                    update omniCases;
                } else {
                    update parentCase;
                }
            }
        }
    }
}