objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand_Privacy_OWA_Name__c</fullName>
        <description>Controlled By Account - This field is the DisplayName of the Brand's Org Wide Email Address. This value must match *exactly* the DisplayName or privacy emails will not send.</description>
        <label>Brand Privacy OWA Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hours_Since_Consumer_Last_Contacted__c</fullName>
        <formula>IF(!ISBLANK(Privacy_Date_Consumer_Last_Contacted__c),
FLOOR(NOW() - Privacy_Date_Consumer_Last_Contacted__c ) * 24
+
FLOOR( MOD( (NOW() - Privacy_Date_Consumer_Last_Contacted__c ) * 24, 24 ) )
,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hours Since Consumer Last Contacted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Resolution_Code__c</fullName>
        <label>Resolution Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Rejected Request</fullName>
                </value>
                <value>
                    <fullName>No Response to follow-up</fullName>
                </value>
                <value>
                    <fullName>Data Not Found</fullName>
                </value>
                <value>
                    <fullName>User Data Provided</fullName>
                </value>
                <value>
                    <fullName>User Data Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Availability Questions</fullName>
                </value>
                <value>
                    <fullName>Quality Concerns</fullName>
                </value>
                <value>
                    <fullName>Sizing Questions</fullName>
                </value>
                <value>
                    <fullName>Care Instructions</fullName>
                </value>
                <value>
                    <fullName>Product Feedback</fullName>
                </value>
                <value>
                    <fullName>Problem Placing Order</fullName>
                </value>
                <value>
                    <fullName>Tracking Order Shipment</fullName>
                </value>
                <value>
                    <fullName>Edit Existing Order</fullName>
                </value>
                <value>
                    <fullName>Cancel Order</fullName>
                </value>
                <value>
                    <fullName>Missing/Damaged Product</fullName>
                </value>
                <value>
                    <fullName>Return Policy</fullName>
                </value>
                <value>
                    <fullName>Returning Order</fullName>
                </value>
                <value>
                    <fullName>Creating Return Label</fullName>
                </value>
                <value>
                    <fullName>Tracking Return</fullName>
                </value>
                <value>
                    <fullName>Return Status</fullName>
                </value>
                <value>
                    <fullName>Signing Up</fullName>
                </value>
                <value>
                    <fullName>Program Questions</fullName>
                </value>
                <value>
                    <fullName>Adding Points</fullName>
                </value>
                <value>
                    <fullName>Redeeming Rewards</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>Password Reset</fullName>
                </value>
                <value>
                    <fullName>Update Information</fullName>
                </value>
                <value>
                    <fullName>Problem Receiving</fullName>
                </value>
                <value>
                    <fullName>Unsubscribe</fullName>
                </value>
                <value>
                    <fullName>Access My Data</fullName>
                </value>
                <value>
                    <fullName>Delete My Data</fullName>
                </value>
                <value>
                    <fullName>Data Owner Request</fullName>
                </value>
                <value>
                    <fullName>Privacy Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Privacy_Intervals__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Intervals to send privacy emails in hours</description>
    <fields>
        <fullName>maxStalledHours__c</fullName>
        <description>The Maximum Number of Hours that a case may be stalled in waiting for consumer response from CSR follow-up before automatically being closed</description>
        <label>maxStalledHours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Privacy Intervals</label>
</CustomObject>

globalValueSets/Brand_Id.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

classes/Batch_PrivacyStalledCaseArchiver.cls
/**
* @author Magnet360
* @date 2019
*
* @group Case
* @group-content ../../ApexDocContent/Case.htm
*
* @description Batch class to resolve privacy cases that have had X hours (from custom settings)
* elapse since last contacted for more information.
* Called hourly from SchedulableBatch_PrivacyIntervalActions
*/
    global class Batch_PrivacyStalledCaseArchiver implements Database.Batchable <sObject>{
    global List<Case> start(Database.BatchableContext bc){
        System.debug('===starting archiver');
        Privacy_Intervals__c orgInterval;
        Integer archiveElapsedHours;

        orgInterval = Privacy_Intervals__c.getValues(Constants.privacyIntervalSettingName);

        archiveElapsedHours = Integer.valueOf(orgInterval.maxStalledHours__c);

        System.debug('===archiveElapsedHours' + archiveElapsedHours);

        return [Select Id, Status, Sub_Type__c, Brand__c, SuppliedEmail, ContactId, Brand_Privacy_OWA_Name__c From Case Where Type = :Constants.privacyCaseType AND Sub_Type__c In :Constants.parentPrivacyCaseSubTypes And Hours_Since_Consumer_Last_Contacted__c >= :archiveElapsedHours And Status = :Constants.waitingForResponse];
    }

    global void execute(Database.BatchableContext bc, List<Case> cases){
        System.debug('===iterating cases' + cases);
        for (Case cse : cases) {
            cse.Status = Constants.resolved;
            cse.Resolution_Code__c = Constants.privacyResolvedStalled;
        }
        update cases;
    }

    global void finish(Database.BatchableContext BC){}

}