objects/Case.object
<CustomObject>
    <fields>
        <fullName>Reason_Code_Details__c</fullName>
        <label>Reason Code Details</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason_Code__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted Forms of Payment</fullName>
                </value>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Account Merge</fullName>
                </value>
                <value>
                    <fullName>Account Registration Error</fullName>
                </value>
                <value>
                    <fullName>Adaptive</fullName>
                </value>
                <value>
                    <fullName>Associate Discount</fullName>
                </value>
                <value>
                    <fullName>Authorization Hold</fullName>
                </value>
                <value>
                    <fullName>BBB Complaint</fullName>
                </value>
                <value>
                    <fullName>Black Friday Complaint</fullName>
                </value>
                <value>
                    <fullName>Brand Protection</fullName>
                </value>
                <value>
                    <fullName>Bulk Buyer Warning</fullName>
                </value>
                <value>
                    <fullName>Business Solicitation</fullName>
                </value>
                <value>
                    <fullName>Cancelled Item</fullName>
                </value>
                <value>
                    <fullName>Cancelled Order</fullName>
                </value>
                <value>
                    <fullName>Cancel Order Request</fullName>
                </value>
                <value>
                    <fullName>Care Instructions</fullName>
                </value>
                <value>
                    <fullName>Check Complaint</fullName>
                </value>
                <value>
                    <fullName>Check Inventory/Restock Inquiry</fullName>
                </value>
                <value>
                    <fullName>Claim Status</fullName>
                </value>
                <value>
                    <fullName>Contest/Sweepstakes</fullName>
                </value>
                <value>
                    <fullName>Corporate Outfitters Request</fullName>
                </value>
                <value>
                    <fullName>Corporate Responsibility</fullName>
                </value>
                <value>
                    <fullName>Corp Social Responsibility</fullName>
                </value>
                <value>
                    <fullName>Counterfeit Merchandise</fullName>
                </value>
                <value>
                    <fullName>Country/State Error</fullName>
                </value>
                <value>
                    <fullName>Coupon Request</fullName>
                </value>
                <value>
                    <fullName>Covet Diamond Request</fullName>
                </value>
                <value>
                    <fullName>Create Return (FEDEX)</fullName>
                </value>
                <value>
                    <fullName>Create Return (NARVAR)</fullName>
                </value>
                <value>
                    <fullName>Customer Accident</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Code__c</fullName>
        <label>Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Loyalty</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Orders</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Sub_detail__c</fullName>
        <label>Reason Sub-detail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason_Code_Details__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Accessories</fullName>
                </value>
                <value>
                    <fullName>Activewear</fullName>
                </value>
                <value>
                    <fullName>Advertisement Feedback</fullName>
                </value>
                <value>
                    <fullName>Associate Behavior</fullName>
                </value>
                <value>
                    <fullName>Bags/Wallets</fullName>
                </value>
                <value>
                    <fullName>Bottoms</fullName>
                </value>
                <value>
                    <fullName>Canadian Return Policy</fullName>
                </value>
                <value>
                    <fullName>Carrier Claim</fullName>
                </value>
                <value>
                    <fullName>Checkout/Cart</fullName>
                </value>
                <value>
                    <fullName>Color</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Products</fullName>
                </value>
                <value>
                    <fullName>Customer Injury</fullName>
                </value>
                <value>
                    <fullName>Customer Profiling</fullName>
                </value>
                <value>
                    <fullName>Damaged Package</fullName>
                </value>
                <value>
                    <fullName>Dead Hyperlink</fullName>
                </value>
                <value>
                    <fullName>Delivered Not Received</fullName>
                </value>
                <value>
                    <fullName>Delivered to Freight Forwarder</fullName>
                </value>
                <value>
                    <fullName>Dresses/Skirts</fullName>
                </value>
                <value>
                    <fullName>Dress Shirts</fullName>
                </value>
                <value>
                    <fullName>Editorial Feedback</fullName>
                </value>
                <value>
                    <fullName>Employment Opportunities</fullName>
                </value>
                <value>
                    <fullName>Employment Verification</fullName>
                </value>
                <value>
                    <fullName>Fashion Event Request</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Fit &amp; Sizing Question</fullName>
                </value>
                <value>
                    <fullName>Footwear</fullName>
                </value>
                <value>
                    <fullName>Fragrances</fullName>
                </value>
                <value>
                    <fullName>General Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Gift Return/Exchange</fullName>
                </value>
                <value>
                    <fullName>Home Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/searchReasonCodeController.cls
public class searchReasonCodeController {

@AuraEnabled 
    public static List<Case> getCases(List<Id> Ids) {
         List<Case> caseList = new List<Case> ();
        
            for(Case cs : [select Id, Reason_Code__c, Reason_Code_Details__c,Reason_Sub_detail__c from Case WHERE Id In :Ids])
            {
               caseList.add(cs); 
            }
        system.debug('caseList==>'+caseList);
         return caseList ;    
    }
    
    @AuraEnabled
  public static List<Case> addParentAccount(String recordId , List<String> lstOfselectedIds){
      system.debug('entered');
      system.debug('lstOfselectedIds==>'+lstOfselectedIds);
    list<Case> lselected = new list<Case>();
      lselected = [select Id, Reason_Code__c, Reason_Code_Details__c,Reason_Sub_detail__c from case where Id =: recordId];
      if( lstOfselectedIds.size() != 0)
      {
      for(Case sId : lselected){
       
        sId.Reason_Code__c = '';
          sID.Reason_Code_Details__c ='';
        
        system.debug('updated');
   }
      }
   update lselected;
      return lselected;
 }
    
    @AuraEnabled
    Public static CaseWrapper getAllCases(string recordId,String objectType, String selectedField){
        List<String> pickListValuesList = new List<String>();
        Schema.SObjectType convertToObj = Schema.getGlobalDescribe().get(objectType);
        Schema.DescribeSObjectResult res = convertToObj.getDescribe();
        Schema.DescribeFieldResult fieldResult = res.fields.getMap().get(selectedField).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }     
       // return pickListValuesList;
        //String PicklistSelected = '';        
       list<Case> caseList = new list<Case>();
      caseList = [select Id, Reason_Code__c, Reason_Code_Details__c,Reason_Sub_detail__c from case where Id =: recordId ];
        
        CaseWrapper relatedCase = new CaseWrapper(Caselist, pickListValuesList); 
        return relatedCase;
    }
        
           @AuraEnabled
         public static List < Case > fetchReasonCode(String searchKeyWord) {
              String searchKey = searchKeyWord + '%';
              List < Case > returnList = new List < Case > ();
             
            //select Reason_Code__c,Reason_Code_Details__c,Reason_Sub_detail__c from ReasonCodeConfiguration__c
              List < Case > lstOfCase = [select Reason_Code__c,Reason_Code_Details__c,Reason_Sub_detail__c from case
                                               where(Reason_Code__c LIKE: searchKey 
                                                     OR Reason_Code_Details__c LIKE: searchKey 
                                                     OR Reason_Sub_detail__c LIKE: searchKey
                                                     ) LIMIT 500];
              for (Case cse: lstOfCase) {
                   returnList.add(cse);
              }
              return returnList;
         }
    
    
   public class CaseWrapper{
        @AuraEnabled
        public list<case> Caselist {get;set;}
        @AuraEnabled
        public list<String> rsCodeList {get;set;}
       // public list<String> rsCodeDetailList {get;set;}
       // public list<String> rsCodeSubList {get;set;}
       public CaseWrapper(list<case> Caselist, list<String> rsCodeList){
       // public CaseWrapper(list<case> Caselist, list<String> rsCodeList, list<String> rsCodeDetailList, list<String> rsCodeSubList){
            this.Caselist = Caselist;
            this.rsCodeList = rsCodeList;
           // this.rsCodeDetailList = rsCodeDetailList;
          //  this.rsCodeSubList = rsCodeSubList;
        }
    }
    
    
    
    
    
    @AuraEnabled
    public static Map<String,String> saveCaseList(List<Case> caseList) {
       
        Map<String,String> resultMap = new Map<String,String>();
       
        try {
               
            update caseList;
            
            resultMap.put('status', 'success');
                resultMap.put('message', 'Case Updated Successfully');        
        }
        catch(Exception e) {
            
            resultMap.put('status', 'error');
                        resultMap.put('message',e.getMessage());
        }
       
        return resultMap;
    }
}