objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Brand_Id__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bass</fullName>
                </value>
                <value>
                    <fullName>Calvin Klein</fullName>
                    <label>Calvin Klein</label>
                </value>
                <value>
                    <fullName>Heritage Ecom</fullName>
                </value>
                <value>
                    <fullName>Izod</fullName>
                </value>
                <value>
                    <fullName>IZOD.com</fullName>
                </value>
                <value>
                    <fullName>Partner Brands</fullName>
                    <label>Partner Brands</label>
                </value>
                <value>
                    <fullName>Speedo</fullName>
                </value>
                <value>
                    <fullName>Style Bureau</fullName>
                    <label>Style Bureau</label>
                </value>
                <value>
                    <fullName>Tommy Hilfiger</fullName>
                </value>
                <value>
                    <fullName>Van Heusen</fullName>
                </value>
                <value>
                    <fullName>Van Heusen.com</fullName>
                    <label>Van Heusen.com</label>
                </value>
                <value>
                    <fullName>Warners.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <fields>
        <fullName>LoyaltyID__c</fullName>
        <externalId>true</externalId>
        <label>Loyalty ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Brand_Id.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

classes/A1TrackerAPIPointsTest.cls
@isTest
public class A1TrackerAPIPointsTest {
     static Map<String, String> responseHeaders = new Map<String, String>();     
    static void testDatasetup(){
        Contact con = new Contact(FirstName='Test',LastName='User',Brand_Id__c='2', LoyaltyID__c='123456789',Email='testUser@nomail.com');
        insert con;
        System.debug(con.Id);
        Case cas = new Case(Origin='Email',Status='New',Brand__c='2',Subject='Test Case',ContactId=con.Id);
        insert cas;
        System.debug('Case contact '+cas.ContactId+'--'+cas.Contact.Brand_Id__c);
    }
    
    @isTest
    static void futurePostTrackerAPIEventstest(){
        Test.startTest();
        testDatasetup();
        List<Case> caseList = new List<Case>();
        Contact con = new Contact(FirstName='Test',LastName='User',Brand_Id__c='2', LoyaltyID__c='123456789',Email='testUser@nomail.com');
        insert con;
        Case cas = new Case(Origin='Email',Status='New',Brand__c='2',Subject='Test Case',ContactId=con.Id);
        caseList.add(cas);
        Case cas1 = new Case(Origin='Email',Status='New',Brand__c='2',Subject='Test Case',ContactId=con.Id);
        caseList.add(cas1);
        Case cas2 = new Case(Origin='Email',Status='New',Brand__c='2',Subject='Test Case',ContactId=con.Id);
        caseList.add(cas2);
        Case cas3 = new Case(Origin='Email',Status='New',Brand__c='2',Subject='Test Case',ContactId=con.Id);
        caseList.add(cas3);
        insert caseList;
        responseHeaders.put('Content-Type', 'application/json');
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                 'OK',
                                                 '{"access_token":"ecdc4492-8a1c-4f03-b9ad-6b9db87f61a1","token_type":"bearer","expires_in":15445210}',
                                                 responseHeaders);
        Test.setMock(HttpCalloutMock.class, fakeResponse);  
        Map<Id,Case> cases = new Map<Id,Case>([SELECT Id FROM Case limit 100]);
        List<Id> caseId = new List<Id>(cases.keySet());
        
        A1TrackerAPIPoints.invokePostTrackerAPIPoints(caseId);
        Test.stopTest();
    }

}