objects/Case.object
<CustomObject>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <description>This field is used to show Country in Personal Data Request Form</description>
        <inlineHelpText>Need to Select the Country of Residence</inlineHelpText>
        <label>Country of Residence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>United States of America (USA)</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia &amp; Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_of_Residence__c</fullName>
        <description>This Field is used to Show States in Personal Data Form</description>
        <inlineHelpText>Need to Select the State of Residence</inlineHelpText>
        <label>State of Residence</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country_of_Residence__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Privacy_Request</fullName>
        <active>true</active>
        <businessProcess>Privacy Request</businessProcess>
        <label>Privacy Request</label>
    </recordTypes>
    <recordTypes>
        <fullName>Support_Case</fullName>
        <active>true</active>
        <businessProcess>Support Case</businessProcess>
        <label>Support Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PersonalDataFormApexControllerTest.cls
/**
 * @author Magnet360
 *
 * @date 2019
 *
 * @description Test Class for PersonalDataFormApexController class. NASSC-98
 *
 * @see PersonalDataFormApexController
 */
@isTest
public class PersonalDataFormApexControllerTest 
{
	@isTest 
    static void getDependentMapTest() 
    {	
            String brandNames = '2';
        	String sourceCountry = 'US';
            Case caseObj = new Case();
        	PersonalDataFormApexController.getDependentMap(caseObj,'Country_of_Residence__c','State_of_Residence__c',brandNames,sourceCountry);
    }
    
    @isTest 
    static void createCaseTestWithUnsubscribe() 
    {	
        PrivacyCaseTests.makeData();
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                         'Complete',
                                         '[{"ResponseMessage":"NEW CUSTOMER","EmailAddress":"test@test.com"}]',
                                         null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        
        Id recordTypeIdPrivacyRequest = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Privacy_Request').getRecordTypeId();
        Id recordTypeIdSupportCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();
        String brandName='2';
        String Country='US';
        List<Case> getCaseList = TestDataFactory.createCases(1);
        getCaseList[0].origin='Web';
        getCaseList[0].Country_of_Residence__c='Canada';
        getCaseList[0].State_of_Residence__c=null;
        getCaseList[0].Type='Unsubscribe';
		getCaseList[0].SuppliedEmail='abc@gmail.com';       
        getCaseList[0].SuppliedPhone='9988998899';
        
        PersonalDataFormApexController.createCase(getCaseList[0], 'test name' , brandName, Country);
       
    }
    
    @isTest 
    static void createCaseTestWithOther() 
    {	
        PrivacyCaseTests.makeData();

        Id recordTypeIdPrivacyRequest = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Privacy_Request').getRecordTypeId();
        Id recordTypeIdSupportCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Support_Case').getRecordTypeId();
        String brandName='2';
        String Country='US';
        List<Case> getCaseList = TestDataFactory.createCases(1);
        getCaseList[0].origin='Web';
        getCaseList[0].Country_of_Residence__c='Canada';
        getCaseList[0].State_of_Residence__c=null;
        getCaseList[0].Type='Access My Data';
		getCaseList[0].SuppliedEmail='abc@gmail.com';       
        getCaseList[0].SuppliedPhone='9988998899';
        
        PersonalDataFormApexController.createCase(getCaseList[0], 'test name' , brandName,Country);
       
    }
}