objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Code_Details__c</fullName>
        <label>Reason Code Details</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason_Code__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Accepted Forms of Payment</fullName>
                </value>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Account Merge</fullName>
                </value>
                <value>
                    <fullName>Account Registration Error</fullName>
                </value>
                <value>
                    <fullName>Adaptive</fullName>
                </value>
                <value>
                    <fullName>Associate Discount</fullName>
                </value>
                <value>
                    <fullName>Authorization Hold</fullName>
                </value>
                <value>
                    <fullName>BBB Complaint</fullName>
                </value>
                <value>
                    <fullName>Black Friday Complaint</fullName>
                </value>
                <value>
                    <fullName>Brand Protection</fullName>
                </value>
                <value>
                    <fullName>Bulk Buyer Warning</fullName>
                </value>
                <value>
                    <fullName>Business Solicitation</fullName>
                </value>
                <value>
                    <fullName>Cancelled Item</fullName>
                </value>
                <value>
                    <fullName>Cancelled Order</fullName>
                </value>
                <value>
                    <fullName>Cancel Order Request</fullName>
                </value>
                <value>
                    <fullName>Care Instructions</fullName>
                </value>
                <value>
                    <fullName>Check Complaint</fullName>
                </value>
                <value>
                    <fullName>Check Inventory/Restock Inquiry</fullName>
                </value>
                <value>
                    <fullName>Claim Status</fullName>
                </value>
                <value>
                    <fullName>Contest/Sweepstakes</fullName>
                </value>
                <value>
                    <fullName>Corporate Outfitters Request</fullName>
                </value>
                <value>
                    <fullName>Corporate Responsibility</fullName>
                </value>
                <value>
                    <fullName>Corp Social Responsibility</fullName>
                </value>
                <value>
                    <fullName>Counterfeit Merchandise</fullName>
                </value>
                <value>
                    <fullName>Country/State Error</fullName>
                </value>
                <value>
                    <fullName>Coupon Request</fullName>
                </value>
                <value>
                    <fullName>Covet Diamond Request</fullName>
                </value>
                <value>
                    <fullName>Create Return (FEDEX)</fullName>
                </value>
                <value>
                    <fullName>Create Return (NARVAR)</fullName>
                </value>
                <value>
                    <fullName>Customer Accident</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Code_Manufacturers__c</fullName>
        <label>Reason Code Manufacturers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accessory Network</fullName>
                </value>
                <value>
                    <fullName>American Essentials</fullName>
                </value>
                <value>
                    <fullName>Basic Resources (VH Socks)</fullName>
                </value>
                <value>
                    <fullName>BCNY</fullName>
                </value>
                <value>
                    <fullName>Calvin Klein Sportswear</fullName>
                </value>
                <value>
                    <fullName>ClearVision Optical</fullName>
                </value>
                <value>
                    <fullName>COTY</fullName>
                </value>
                <value>
                    <fullName>Customer Leather</fullName>
                </value>
                <value>
                    <fullName>Cutie Pie Baby (100364)</fullName>
                </value>
                <value>
                    <fullName>Delta Galil</fullName>
                </value>
                <value>
                    <fullName>Estee</fullName>
                </value>
                <value>
                    <fullName>Fishman &amp; Tobin (477)</fullName>
                </value>
                <value>
                    <fullName>Fletcher</fullName>
                </value>
                <value>
                    <fullName>G-III Apparel Group (54163)</fullName>
                </value>
                <value>
                    <fullName>Global Brands Group</fullName>
                </value>
                <value>
                    <fullName>Harbor Footwear</fullName>
                </value>
                <value>
                    <fullName>Himatsingka (33699)</fullName>
                </value>
                <value>
                    <fullName>Internal Wholesale</fullName>
                </value>
                <value>
                    <fullName>Jimlar</fullName>
                </value>
                <value>
                    <fullName>Kayser-Roth Corp.</fullName>
                </value>
                <value>
                    <fullName>Kids Headquarters</fullName>
                </value>
                <value>
                    <fullName>LF Home</fullName>
                </value>
                <value>
                    <fullName>Marc Fisher</fullName>
                </value>
                <value>
                    <fullName>Marchon (77169)</fullName>
                </value>
                <value>
                    <fullName>Marcraft</fullName>
                </value>
                <value>
                    <fullName>Max Leather</fullName>
                </value>
                <value>
                    <fullName>Movado</fullName>
                </value>
                <value>
                    <fullName>Nourison</fullName>
                </value>
                <value>
                    <fullName>Pacific Coast Feather (19648)</fullName>
                </value>
                <value>
                    <fullName>Peerless</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Code__c</fullName>
        <label>Reason Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Loyalty</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Orders</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Returns</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Technical</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Sub_detail__c</fullName>
        <label>Reason Sub-detail</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason_Code_Details__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Accessories</fullName>
                </value>
                <value>
                    <fullName>Activewear</fullName>
                </value>
                <value>
                    <fullName>Advertisement Feedback</fullName>
                </value>
                <value>
                    <fullName>Associate Behavior</fullName>
                </value>
                <value>
                    <fullName>Bags/Wallets</fullName>
                </value>
                <value>
                    <fullName>Bottoms</fullName>
                </value>
                <value>
                    <fullName>Canadian Return Policy</fullName>
                </value>
                <value>
                    <fullName>Carrier Claim</fullName>
                </value>
                <value>
                    <fullName>Checkout/Cart</fullName>
                </value>
                <value>
                    <fullName>Color</fullName>
                </value>
                <value>
                    <fullName>Cosmetic Products</fullName>
                </value>
                <value>
                    <fullName>Customer Injury</fullName>
                </value>
                <value>
                    <fullName>Customer Profiling</fullName>
                </value>
                <value>
                    <fullName>Damaged Package</fullName>
                </value>
                <value>
                    <fullName>Dead Hyperlink</fullName>
                </value>
                <value>
                    <fullName>Delivered Not Received</fullName>
                </value>
                <value>
                    <fullName>Delivered to Freight Forwarder</fullName>
                </value>
                <value>
                    <fullName>Dresses/Skirts</fullName>
                </value>
                <value>
                    <fullName>Dress Shirts</fullName>
                </value>
                <value>
                    <fullName>Editorial Feedback</fullName>
                </value>
                <value>
                    <fullName>Employment Opportunities</fullName>
                </value>
                <value>
                    <fullName>Employment Verification</fullName>
                </value>
                <value>
                    <fullName>Fashion Event Request</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Fit &amp; Sizing Question</fullName>
                </value>
                <value>
                    <fullName>Footwear</fullName>
                </value>
                <value>
                    <fullName>Fragrances</fullName>
                </value>
                <value>
                    <fullName>General Sponsorship</fullName>
                </value>
                <value>
                    <fullName>Gift Return/Exchange</fullName>
                </value>
                <value>
                    <fullName>Home Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZdPVHDateofServiceIssue__c</fullName>
        <label>Date of Service Issue</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ZdPVHDistrictNumber__c</fullName>
        <label>District Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZdPVHManufacturer__c</fullName>
        <label>Manufacturer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZdPVHProductCategory__c</fullName>
        <label>Product Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZdPVHStoreNumber__c</fullName>
        <label>Store Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZdPVHUpdateAccountInfoReason__c</fullName>
        <label>Update Account Info Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Brand_Id__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bass</fullName>
                </value>
                <value>
                    <fullName>Calvin Klein</fullName>
                    <label>Calvin Klein</label>
                </value>
                <value>
                    <fullName>Heritage Ecom</fullName>
                </value>
                <value>
                    <fullName>Izod</fullName>
                </value>
                <value>
                    <fullName>IZOD.com</fullName>
                </value>
                <value>
                    <fullName>Partner Brands</fullName>
                    <label>Partner Brands</label>
                </value>
                <value>
                    <fullName>Speedo</fullName>
                </value>
                <value>
                    <fullName>Style Bureau</fullName>
                    <label>Style Bureau</label>
                </value>
                <value>
                    <fullName>Tommy Hilfiger</fullName>
                </value>
                <value>
                    <fullName>Van Heusen</fullName>
                </value>
                <value>
                    <fullName>Van Heusen.com</fullName>
                    <label>Van Heusen.com</label>
                </value>
                <value>
                    <fullName>Warners.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Brand_Id.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

classes/ReasonCodeButtonConrollerTest.cls
@isTest
public class ReasonCodeButtonConrollerTest {
    
   @isTest
     static void TestButtonControllerMethod ()
    {
        
        List<string> reasonManufaList=new List<string>();
        Account acc = new Account();
        acc.Name = 'generic Account' + Math.random();
        insert acc;
        
        Contact con = new Contact();
        con.email = 'foo@example.com';
        con.lastName = 'generic contact ' + Math.random();
        con.AccountId = acc.id;
        con.Brand_Id__c='9';
        insert con;

        
        Case parentcse = new Case();
        parentcse.ContactId=con.Id;
        parentcse.AccountId=acc.Id;
        parentcse.Origin='Email';
        parentcse.Brand__c='2';
        parentcse.Status='Open';
        parentcse.RecordTypeId=Constants.supportCaseRecordTypeId;
        parentcse.Reason_Code__c = 'hy';
        parentcse.Reason_Code_Details__c = 'khy';
        parentcse.Reason_Sub_detail__c = 'nothing';
        insert parentcse ;
        
        Case cse = new Case();
        cse.ParentId=parentcse.id;
        cse.Brand__c='9';
        cse.ContactId=con.Id;
        cse.AccountId=acc.Id;
        cse.RecordTypeId=Constants.supportCaseRecordTypeId;
        insert cse ;
        
        
        cse.Reason_Code__c = 'Corporate';
        cse.Reason_Code_Details__c = 'Human Resource';
        cse.Reason_Sub_detail__c = 'nothing';
        cse.ZdPVHDateofServiceIssue__c = date.today();
        cse.ZdPVHStoreNumber__c = '58';
        cse.ZdPVHDistrictNumber__c = '345';
        cse.ZdPVHUpdateAccountInfoReason__c = 'poor';
        cse.ZdPVHManufacturer__c='Test';
        cse.ZdPVHProductCategory__c='Test';
        cse.Reason_Code_Manufacturers__c='Test1';
       cse.Reason_Code_Product_Category__c = 'test2';
        update cse ;
        
        String recordId = cse.id;
        String grandParent = cse.Reason_Code__c;
        String parentField = cse.Reason_Code_Details__c;
        String childField = cse.Reason_Sub_detail__c;
        date dateofServiceIssue = date.today();
        String storeNumber = cse.ZdPVHStoreNumber__c ;
        String districtNumber = cse.ZdPVHDistrictNumber__c;
        String updateAccountInfoReason = cse.ZdPVHUpdateAccountInfoReason__c ;
        string manufacturer= cse.ZdPVHManufacturer__c;
        string productCategory=cse.ZdPVHProductCategory__c;
        string reasonManu=cse.Reason_Code_Manufacturers__c;
            reasonManufaList.add(reasonManu);
      
        
        string contrfieldApiName=cse.Reason_Code__c;
        string depfieldApiName=cse.Reason_Code_Details__c;
        String controllingField = contrfieldApiName.toLowerCase();
        String dependentField = depfieldApiName.toLowerCase();
        integer val=10;
        string validFor1='test';
        string active='true';
        String defaultValue='test';
        String value='testing';
        Map<String, List<String>> lstPick1=ReasonCodeButtonController.getDependentPicklist(cse,'Reason_Code__c','Reason_Code_Details__c');
       //List <String> selectOpManu=ReasonCodeButtonController.getselectOptions(cse,cse.Reason_Code_Manufacturers__c);
       //List<String> lstString = ReasonCodeButtonController.getselectOptions(cse , 'reasonManu');
     

       Test.starttest();
         //List <String> selectManu=ReasonCodeButtonController.getselectOptions(cse,'reasonManu');
        
          List<Case> result = ReasonCodeButtonController.updateCase ( recordId , grandParent, parentField, childField , dateofServiceIssue,  storeNumber ,  districtNumber, updateAccountInfoReason,manufacturer,productCategory);
        // List <String> selectOp=ReasonCodeButtonController.getselectOptions(cse,productCategory);
           string decimalToBinary=ReasonCodeButtonController.decimalToBinary(val);
           string base64ToBits=ReasonCodeButtonController.base64ToBits(validFor1);
           ReasonCodeButtonController.PicklistEntryWrapper testWrapper = new ReasonCodeButtonController.PicklistEntryWrapper(); 
              active =testWrapper.active;
              defaultValue =testWrapper.defaultValue;
              String label =testWrapper.label;
               value =testWrapper.value;
              String validFor =testWrapper.validFor;
             
           
           Map<String, List<String>> picklistValues=ReasonCodeButtonController.getDependentPicklist(cse,contrfieldApiName,depfieldApiName );
             List<String> selectionoptions = ReasonCodeButtonController.getselectOptions(cse , 'Reason_Code_Product_Category__c' );
        Test.stopTest() ;
        
        
    }
    
   
        
    

}