objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Brand_Id__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Brand_Id</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CreatedByMethod__c</fullName>
        <label>Created By Method</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email</fullName>
    </fields>
    <fields>
        <fullName>EmailOptInDate__c</fullName>
        <label>Email Opt-in Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EmailOptInStatus__c</fullName>
        <label>Email Opt-in</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EmailOptOutDate__c</fullName>
        <label>Email Opt-out Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>HomeStore__c</fullName>
        <label>HomeStore</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Latest_Source__c</fullName>
        <label>Latest Source System</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoyaltyFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LoyaltyFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loyalty_Optin_Date__c</fullName>
        <label>Loyalty Optin Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PVHCreatedDate__c</fullName>
        <label>PVHCreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SMSNumber__c</fullName>
        <label>SMSNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>SMSOptInDate__c</fullName>
        <label>SMS Opt-in Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SMSOptOutDate__c</fullName>
        <label>SMS Opt-out Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SMSOptinStatus__c</fullName>
        <label>SMS Opt-in</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Source from Outside Lists.</description>
        <inlineHelpText>Source from Outside Lists.</inlineHelpText>
        <label>Source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StoreOfCapture__c</fullName>
        <label>Store Of Capture</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Email</fullName>
        <active>true</active>
        <label>Email</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LoyaltySettings__mdt.object
<CustomObject>
    <fields>
        <fullName>BrandId__c</fullName>
        <label>BrandId</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsLoyaltyApplicable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this brand is part of Loyalty program or not.</description>
        <label>IsLoyaltyApplicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Brand__c</fullName>
        <label>Parent Brand</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>LoyaltySettings</label>
    <pluralLabel>LoyaltySettings</pluralLabel>
</CustomObject>

objects/SharedSecret__mdt.object
<CustomObject>
    <fields>
        <fullName>Secret__c</fullName>
        <label>Secret</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Shared Secret</label>
    <pluralLabel>Shared Secrets</pluralLabel>
</CustomObject>

globalValueSets/Brand_Id.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Tommy Hilfiger</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Calvin Klein</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>IZOD</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Van Heusen</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Speedo USA</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Heritage Ecom</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Partner Brands</label>
    </customValue>
    <customValue>
        <fullName>81</fullName>
        <label>IZOD.com</label>
    </customValue>
    <customValue>
        <fullName>83</fullName>
        <label>Warner</label>
    </customValue>
    <customValue>
        <fullName>84</fullName>
        <label>Style Bureau</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>True&amp;Co</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Olga</label>
    </customValue>
    <customValue>
        <fullName>100</fullName>
        <label>100 - Unknown from Zendesk</label>
    </customValue>
    <customValue>
        <fullName>82</fullName>
        <label>Van Heusen.com (VHE)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <isActive>false</isActive>
        <label>3</label>
    </customValue>
    <masterLabel>Brand Id</masterLabel>
</GlobalValueSet>

classes/ChargeItSpotSignUp.cls
/*
*  {"context":{"locale":"en_US","timezone":"PST8PDT","library":{"name":"analytics-java","version":"analytics/2.0.0-RC3"}},"integrations":{},"messageId":"52b3947f-23bc-4454-96e6-f33bcbf920ae","timestamp":"2018-08-08T14:29:33.795Z","traits":{"brand":"TH Store number 083","email":"YYZ@GMAIL.COM","emailExplicitOptinRequired":"false","emailOptin":"false","location":"TestLocation","serialNumber":"12345","site":"SiteName","smsExplicitOptinRequired":"false","smsOptin":"true","source":"ChargeItSpot","storeNumber":"1234"},"type":"identify","userId":"7785551212","writeKey":"somewritekey","receivedAt":"2018-08-08T14:29:37.795Z","sentAt":"2018-08-08T14:29:37.000Z","originalTimestamp":"2018-08-08T14:29:33+0000"}
* 
* Json request body sample from Segment.io
* {"messageId":"test-message-mkn7f6","timestamp":"2019-07-11T13:26:57.397Z","type":"identify","email":"test@example.org","projectId":"PWJdr2j1VW","traits":{"trait1":1,"trait2":"test","trait3":true},"userId":"test-user-wtg88h"}
* Note: For HMAC authentication json format changes the digest
* 
* Header
* X-Signature: 61438bde8f48b89b310aa972fd92d7831d2d70c7
* 
* https://instance.salesforce.com/services/apexrest/ChargeItSpot/SignUp

ChageItSpot request comes only for brand 1 (Tommy (TH))
* 	NASSC-1087
	NASSC-1138: Update ChageItSpot for brand parameter changes
	NASSC-1311 
*/

@RestResource(urlMapping='/ChargeItSpot/SignUp')
global without sharing class ChargeItSpotSignUp {
    static DateTime chargeItTimeStamp;
    static Id intOwnerId;


    global class ChargItReq{
        public context context;
        public integration integrations;
        public String messageId;
        public String timestamp;
        public trait traits;
        public String type;
        public String userId;  //represents SMS Phone number
        public String writeKey;
        public String receivedAt;
        public String sentAt;
        public String originalTimestamp;       
    }
    
    global class context{
        public String locale;
        public String timezone;
        public library library;
    }
    
    global class library{
        public String name;
        public String version;
    }
    
    global class integration{}
    
    global class trait{
        public String brand;
        public String email;
        public String emailExplicitOptinRequired;
        public String emailOptin;
        public String location;
        public String serialNumber;
        public String site;
        public String smsExplicitOptinRequired;
        public String smsOptin;
        public String source;
        public String storeNumber;
    }
    
    global class ChargeItResponse{
        public String code;
        public String message;
    }
    
    global static boolean authenticateRequest(RestRequest req){
        Boolean validRequester = false;
        
        string sharedSecret =  [SELECT Secret__c FROM SharedSecret__mdt WHERE DeveloperName = 'ChargeItSpot' LIMIT 1].Secret__c;
        system.debug('sharedSecret: ' + sharedSecret);
        
        String xsignature = req.headers.get('X-Signature');
        system.debug('*Request xsignature: ' + xsignature);
        
        if(xsignature != Null && String.isNotBlank(xsignature)){
            Blob digest = Crypto.generateMac('hmacSHA1', req.requestBody, Blob.valueOf(sharedSecret));   
            system.debug('digest hex: '+ EncodingUtil.convertToHex(digest));  
            if(EncodingUtil.convertToHex(digest) == xsignature) validRequester = true;
        } 
        return validRequester;    
    }    
    
    @HttpPost
    global static ChargeItResponse doSignUp(){
        Boolean authenticated = false;  
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        ChargeItResponse chargeItResponse = new ChargeItResponse();

        Contact SMSMatchedContact = new Contact();
        Contact emailMatchedContact = new Contact();
        Boolean smsAndEmailExactMatch = false;
        List<SignUpActivity> signUpActivityList = new List<SignUpActivity>();
        String brandId;
        Contact newContact;
        Contact toBeUpdatedContact;
        
        authenticated = authenticateRequest(req);
        
        if(authenticated){
            String requestData = req.requestBody.toString();
            ChargItReq chgItReq = (ChargItReq)json.deserialize(requestData, ChargItReq.class);
            
            // Brand, email or userId not present in request, return error message
            if(String.isBlank(chgItReq.traits.brand) || String.isBlank(chgItReq.traits.email) || String.isBlank(chgItReq.userId) || !SFMCUtility.validateEmail(chgItReq.traits.email))
            {
                res.statusCode = 400;
                chargeItResponse.code = 'MISSING_REQ_PARAMS';
                chargeItResponse.message = 'Missing brand/email/userId or invalid email';
                return chargeItResponse;
            }
            // if both emailOptin & smsOptin are missing, or if both are false, do nothing..
            else if ((String.isBlank(chgItReq.traits.emailOptin) && String.isBlank(chgItReq.traits.smsOptin)) && (!Boolean.valueOf(chgItReq.traits.emailOptin) && !Boolean.valueOf(chgItReq.traits.smsOptin)) )
            {
                // do nothing..

            }
            else { //all req params exist
                
                String[] reqBrandArray = chgItReq.traits.brand.split(' ');
                String reqBrand = reqBrandArray[0];
                System.debug('### reqBrand: ' + reqBrand);
                if (String.isBlank(chgItReq.timestamp)) chargeItTimeStamp = UtilityClass.strYYYMMDDtoDateTime(chgItReq.timestamp);

                List <User> IntegrationUsers = [SELECT Id FROM User WHERE Profile.Name='PVHIntegrationAPIUser' AND IsActive = true LIMIT 1];
                if (IntegrationUsers.size()>0) {
                    intOwnerId = IntegrationUsers[0].Id;
                }

                List<LoyaltySettings__mdt> listLoyaltySettingList = [Select Id,BrandId__c,IsLoyaltyApplicable__c,Parent_Brand__c, DeveloperName 
                                                                     FROM LoyaltySettings__mdt 
                                                                     WHERE DeveloperName  = :reqBrand ];
                if(listLoyaltySettingList.size()>0) {
                    

                    brandId = listLoyaltySettingList[0].BrandId__c;


                    SMSMatchedContact = SFMCUtility.searchSMSBrandContact(brandId,chgItReq.userId);
                    emailMatchedContact = SFMCUtility.searchEmailBrandContact(brandId, chgItReq.traits.email);
                    if (SMSMatchedContact!=null && SMSMatchedContact.Email!=null && SMSMatchedContact.Email==chgItReq.traits.email) smsAndEmailExactMatch = true;

                    if (!Boolean.valueOf(chgItReq.traits.smsOptin) && Boolean.valueOf(chgItReq.traits.emailOptin)) {

                        if (emailMatchedContact==null){
                            // create new contact with email, smsnumber, emailoptin, loyaltyopin

                        } else {
                            // update contact with SMS number, emailoptin, loyalty optin
                        }


                    } else if (Boolean.valueOf(chgItReq.traits.smsOptin)) {

                        if (smsAndEmailExactMatch) {
                            // reoptin#1  - update SMSMatchedContact with smsOptin = 'P', loyalty opin - callout

                        } else if (SMSMatchedContact==null && emailMatchedContact==null){
                            // optin#1 - create new contact with email, smsnumber, smsOptin='P', emailoptin, loyaltyopin - callout

                        } else if (SMSMatchedContact!=null && emailMatchedContact==null){
                            //only sms match found
                            if (SMSMatchedContact.Email==null){
                                // reoptin#5  - update SMSMatchedContact with Email, smsOptin = 'P', loyalty opin, emailOptin - callout
                            } else {
                                // reoptin#4A  - update SMSMatchedContact with  smsOptin = 'P', loyalty opin - callout

                                if (Boolean.valueOf(chgItReq.traits.emailOptin)) {
                                    // reoptin#4B - create new contact with email, emailoptin, loyaltyopin; accId & loyaltyId from smsMatchedContact
                                }

                            }

                        } else if (SMSMatchedContact==null && emailMatchedContact!=null){
                            //only email match found
                            // optin#2,3
                            if (emailMatchedContact.SMSNumber__c==null){
                                // optin#2 - update emailMatchedContact with SMSNumber, SMSOptin = 'P', loyalty flag, email optin -- callout




                            } else {
                                // optin#3
                                // create new contact with smsnumber, smsOptin = Y, loyaltyopin; accId & loyalty id from emailMatchedContact
                                newContact = createNewSMSOnlyContact(chgItReq, brandId);

                                if (Boolean.valueOf(chgItReq.traits.emailOptin)) {
                                    //update emailMatchedContact's loyalty optin & emailoptin
                                }

                            }

                        } else if (SMSMatchedContact!=null && emailMatchedContact!=null && !smsAndEmailExactMatch){
                                //separate sms and email matched contacts found
                                // reoptin#2, 3, 6, 7 - updated SMSMatchedContact smsOptin = 'P', loyalty -- callout
                                if (Boolean.valueOf(chgItReq.traits.emailOptin)) {
                                    //update emailMatchedContact's loyalty optin & emailoptin
                                }

                        }

                    }


  /**                  contacts = [SELECT Id, FirstName, LastName, Email, Brand_Id__c, Source_System__c, Latest_Source__c, StoreOfCapture__c, HomeStore__c, EmailOptInStatus__c, SMSOptinStatus__c, MobilePhone
                                FROM Contact 
                                WHERE Brand_Id__c =: BrandId AND Email =: chgItReq.traits.email LIMIT 1];
                    //Check for existing Contact information, if Present update it, else create New Contact
                    if(contacts.size()>0){ 
                        Contact updatedContact = updateContact(contacts[0],chgItReq);
                        signUpActivityList.add(SignUpActivity.signupActivity(updatedContact.Id, updatedContact.Latest_Source__c,updatedContact.Brand_Id__c));
                        res.statusCode = 200;
                        chargeItResponse.code = 'OK';
                        chargeItResponse.message = 'Success';
                    } else{
                        Contact createdContact = createContact(chgItReq, BrandId);
                        signUpActivityList.add(SignUpActivity.signupActivity(createdContact.Id, createdContact.Latest_Source__c,createdContact.Brand_Id__c));
                        res.statusCode = 200;
                        chargeItResponse.code = 'OK';
                        chargeItResponse.message = 'Success';
                    }
       **/

                    if(signUpActivityList.size()>0) SignUpActivity.logSignUpActivity(signUpActivityList);                    
                }
            }            
        } else { //Invalid Shared Secret key
            res.statusCode = 400;
            chargeItResponse.code = 'AUTHENTICATION_FAILED';
            chargeItResponse.message = 'Incorrect shared secret';
        }
        return chargeItResponse;
    }
    
    

    
    
    //Create Contact
    Static Contact createNewSMSOnlyContact(ChargItReq chgItReq, String brandId){

        Contact con = new Contact();

        if(intOwnerId!=null) con.OwnerId = intOwnerId;
        if(String.isNotBlank(chgItReq.traits.email)) con.Email = chgItReq.traits.email;
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Email').getRecordTypeId();

        con.Source_System__c = 'ChargeItSpot'; //chgItReq.traits.source;
        con.Latest_Source__c = 'ChargeItSpot'; //chgItReq.traits.source;


        con.Source__c = 'ChargeItSpot';
        con.Brand_Id__c = brandId;
        con.createdByMethod__c = 'API';
        if (chargeItTimeStamp!=null) con.PVHCreatedDate__c = chargeItTimeStamp;

        con.Status__c = 'ACTIVE';
        con.LastName = 'Unknown';   //LastName is set to 'Unknown'
        con.FirstName = 'Unknown';   //LastName is set to 'Unknown'
        if(String.isNotBlank(chgItReq.traits.storeNumber)) con.HomeStore__c = chgItReq.traits.storeNumber;
        if(String.isNotBlank(chgItReq.traits.storeNumber)) con.StoreOfCapture__c = chgItReq.traits.storeNumber;

        if(String.isNotBlank(chgItReq.userId)) con.MobilePhone = chgItReq.userId;
        if(String.isNotBlank(chgItReq.traits.smsOptin) && Boolean.valueOf(chgItReq.traits.smsOptin) == true){
            con.SMSOptinStatus__c = 'P'; //true;
            con.LoyaltyFlag__c = true;
            if (chargeItTimeStamp!=null) {
                con.SMSOptInDate__c = chargeItTimeStamp;
                con.Loyalty_Optin_Date__c = chargeItTimeStamp;
            }


        }


       return con;
       
    
    }

    public static Contact createNewSMSAndEmailContact(ChargItReq chgItReq, String brandId){
        Contact con = createNewSMSOnlyContact(chgItReq, brandId);
        con.Email = chgItReq.traits.email;

        if(String.isNotBlank(chgItReq.traits.emailOptIn) && Boolean.valueOf(chgItReq.traits.emailOptIn) == true){

            con.EmailOptInStatus__c = 'Y'; //true;
            if (!con.LoyaltyFlag__c) con.LoyaltyFlag__c = true;
            if (chargeItTimeStamp!=null) con.EmailOptInDate__c = chargeItTimeStamp;
        }
        return con;

    }
    
    //Set contact email preferences
    Static void setContactEmailOptin(Contact cont,Boolean emailOptInFlag){
        if (emailOptInFlag){ 
            cont.EmailOptInStatus__c = 'Y'; //true;
            cont.EmailOptInDate__c = System.now();
            cont.HasOptedOutOfEmail = false;
            cont.EmailOptOutDate__c = Null;
        } else {
            cont.EmailOptInStatus__c = 'N'; //false;
            cont.EmailOptInDate__c = Null;
            cont.HasOptedOutOfEmail = true;
            cont.EmailOptOutDate__c = System.now();
        }
    }
    
    
    //Set contact SMS preferences
    Static void setContactSMSOptin(Contact cont,Boolean smsOptInFlag){
        if (smsOptInFlag){ 
            cont.SMSOptinStatus__c = 'Y'; //true;
            cont.SMSOptInDate__c = System.now();
            cont.SMSOptOutDate__c = Null;
        } else {
            cont.SMSOptinStatus__c = 'N'; //false;
            cont.SMSOptInDate__c = Null;
            cont.SMSOptOutDate__c = System.now();
        }
    }
    

    
    
}